// ──────────────────────────────────────────────────
// EMBODIED CARBON DATA - ICE DATABASE v4.1
// ──────────────────────────────────────────────────
// Primary source: ICE Database (Inventory of Carbon & Energy) v4.1
//   - Circular Ecology (formerly University of Bath)
//   - https://circularecology.com/embodied-carbon-footprint-database.html
//   - Version: v4.1 (October 2025)
//   - Key v4.1 changes from v3.0:
//     • GGBS/BFS now uses economic allocation per EN 15804+A2 (higher values)
//     • Bitumen/asphalt updated with latest Eurobitume LCA data
//     • New materials added: geopolymer concrete, bio-based products, MEP
//     • Updated steel values reflecting UK decarbonisation progress
//     • Timber biogenic carbon reporting aligned with EN 15804+A2
//
// Supplementary sources:
//   - RICS Professional Statement: Whole Life Carbon Assessment (2nd ed. 2023)
//   - IStructE: How to Calculate Embodied Carbon (2nd ed. 2022)
//   - BSRIA BG 76/2014: Embodied Carbon - The Inventory of Carbon and Energy
//   - Manufacturer-published EPDs (Environmental Product Declarations) via EPD Hub
//   - LETI Climate Emergency Design Guide (2020)
//   - RIBA 2030 Climate Challenge
//
// IMPORTANT: These values are representative industry averages for the UK
// market. They are suitable for early-stage carbon estimation and awareness.
// For design-stage decisions, always use project-specific EPD data from the
// actual product manufacturer. Modules covered: A1–A3 (cradle-to-gate) unless
// otherwise noted. All values in kgCO₂e per kg of material.
// ──────────────────────────────────────────────────

export interface MaterialData {
  id: string;
  name: string;
  category: string;
  embodiedCarbon: number; // kgCO2e/kg
  unit: string;
  density?: number; // kg/m³
  notes?: string;
  alternatives?: string[];
  fhsRecommended?: boolean; // aligns with Future Homes Standard guidance
  typicalApplications?: string; // where it's commonly specified
}

// LETI / RIBA 2030 embodied carbon benchmarks (kgCO2e/m² GIA)
// LETI targets cover modules A1-A5; RIBA 2030 v2 covers A1-A5, B1-B5, C1-C4
export const carbonBenchmarks = {
  leti: {
    label: "LETI 2020 Target",
    residential: 500,
    office: 600,
    school: 550,
    retail: 550,
  },
  riba2030: {
    label: "RIBA 2030 Target",
    residential: 625,
    office: 750,
    school: 700,
    retail: 700,
  },
  businessAsUsual: {
    label: "Business as Usual",
    residential: 1000,
    office: 1200,
    school: 1100,
    retail: 1100,
  },
} as const;

export type BuildingType = "residential" | "office" | "school" | "retail";

export const materialCategories = [
  "Concrete & Cement",
  "Steel & Metals",
  "Timber & Wood",
  "Insulation",
  "Glass",
  "Bricks & Blocks",
  "Plastics & Polymers",
  "Aggregates",
  "Plaster & Render",
  "Roofing",
  "Flooring",
  "Waterproofing & Membranes",
  "Adhesives & Sealants",
  "Paints & Coatings",
  "Pipes & Drainage",
  "MEP & Services",
  "Fixings & Connections",
  "Asphalt & Bituminous",
  "Geotextiles & Ground",
  "Fire Protection",
] as const;

export const iceDatabase: MaterialData[] = [
  /* ═══════════════════════════════════════
     CONCRETE & CEMENT
     ═══════════════════════════════════════ */
  {
    id: "concrete-general",
    name: "General Concrete (RC 32/40)",
    category: "Concrete & Cement",
    embodiedCarbon: 0.132,
    unit: "kgCO2e/kg",
    density: 2400,
    notes: "Typical reinforced concrete mix",
    alternatives: ["concrete-ggbs", "concrete-pfa", "concrete-lc3"],
    typicalApplications: "Foundations, frames, slabs, retaining walls",
  },
  {
    id: "concrete-ggbs",
    name: "Concrete with 50% GGBS",
    category: "Concrete & Cement",
    embodiedCarbon: 0.097,
    unit: "kgCO2e/kg",
    density: 2400,
    notes: "GGBS cement replacement. ICE v4.1 applies economic allocation per EN 15804+A2 - value higher than v3.0 (0.089) but still ~27% less than general concrete.",
    fhsRecommended: true,
    typicalApplications: "Foundations, slabs, marine structures",
  },
  {
    id: "concrete-pfa",
    name: "Concrete with 30% PFA",
    category: "Concrete & Cement",
    embodiedCarbon: 0.103,
    unit: "kgCO2e/kg",
    density: 2400,
    notes: "Pulverised fuel ash replacement - 22% less carbon",
    fhsRecommended: true,
    typicalApplications: "General structural, foundations, floor slabs",
  },
  {
    id: "portland-cement",
    name: "Portland Cement (CEM I)",
    category: "Concrete & Cement",
    embodiedCarbon: 0.912,
    unit: "kgCO2e/kg",
    density: 1500,
    notes: "Ordinary Portland Cement - most carbon-intensive binder",
    alternatives: ["concrete-ggbs", "concrete-pfa", "concrete-lc3"],
    typicalApplications: "Binder in concrete, mortar, render",
  },
  {
    id: "precast-concrete",
    name: "Precast Concrete",
    category: "Concrete & Cement",
    embodiedCarbon: 0.176,
    unit: "kgCO2e/kg",
    density: 2400,
    notes: "Factory-produced concrete elements",
    alternatives: ["concrete-ggbs", "clt"],
    typicalApplications: "Floor planks, wall panels, stairs, cladding",
  },
  {
    id: "concrete-lc3",
    name: "LC3 Cement Concrete",
    category: "Concrete & Cement",
    embodiedCarbon: 0.079,
    unit: "kgCO2e/kg",
    density: 2380,
    notes: "Limestone Calcined Clay Cement - up to 40% less carbon than CEM I mixes",
    fhsRecommended: true,
    typicalApplications: "General structural, foundations, slabs",
  },
  {
    id: "concrete-fibre-reinforced",
    name: "Fibre-Reinforced Concrete",
    category: "Concrete & Cement",
    embodiedCarbon: 0.149,
    unit: "kgCO2e/kg",
    density: 2400,
    notes: "Steel or synthetic fibres replace some traditional rebar",
    alternatives: ["concrete-ggbs", "concrete-pfa"],
    typicalApplications: "Industrial floors, tunnel linings, slabs on grade",
  },
  {
    id: "concrete-lightweight",
    name: "Lightweight Aggregate Concrete",
    category: "Concrete & Cement",
    embodiedCarbon: 0.108,
    unit: "kgCO2e/kg",
    density: 1850,
    notes: "Uses expanded clay/shale aggregates - lighter and lower carbon",
    typicalApplications: "Upper floor slabs, infill panels, roof decks",
  },
  {
    id: "concrete-screed",
    name: "Floor Screed (Cement-Sand)",
    category: "Concrete & Cement",
    embodiedCarbon: 0.143,
    unit: "kgCO2e/kg",
    density: 2000,
    typicalApplications: "Floor levelling layer over structural slab",
  },

  /* ═══════════════════════════════════════
     STEEL & METALS
     ═══════════════════════════════════════ */
  {
    id: "steel-structural",
    name: "Structural Steel (UK Average)",
    category: "Steel & Metals",
    embodiedCarbon: 1.55,
    unit: "kgCO2e/kg",
    density: 7850,
    notes: "Average UK structural steel sections",
    alternatives: ["steel-recycled", "clt", "glulam"],
    typicalApplications: "Structural frames, beams, columns",
  },
  {
    id: "steel-recycled",
    name: "Recycled Steel (EAF)",
    category: "Steel & Metals",
    embodiedCarbon: 0.47,
    unit: "kgCO2e/kg",
    density: 7850,
    notes: "Electric arc furnace from scrap - 70% less carbon",
    fhsRecommended: true,
    typicalApplications: "Structural frames, beams, columns",
  },
  {
    id: "steel-rebar",
    name: "Steel Reinforcement (Rebar)",
    category: "Steel & Metals",
    embodiedCarbon: 1.99,
    unit: "kgCO2e/kg",
    density: 7850,
    notes: "Reinforcing bar for concrete",
    alternatives: ["steel-rebar-recycled"],
    typicalApplications: "Reinforced concrete structures",
  },
  {
    id: "steel-rebar-recycled",
    name: "Recycled Rebar (UK EAF)",
    category: "Steel & Metals",
    embodiedCarbon: 0.84,
    unit: "kgCO2e/kg",
    density: 7850,
    notes: "EAF-produced rebar from scrap - 58% less carbon",
    fhsRecommended: true,
    typicalApplications: "Reinforced concrete structures",
  },
  {
    id: "steel-galvanised",
    name: "Galvanised Steel",
    category: "Steel & Metals",
    embodiedCarbon: 1.62,
    unit: "kgCO2e/kg",
    density: 7850,
    notes: "Hot-dip zinc coated for corrosion resistance",
    alternatives: ["steel-recycled"],
    typicalApplications: "Lintels, purlins, external fixings, cladding rails",
  },
  {
    id: "steel-cladding",
    name: "Profiled Steel Cladding",
    category: "Steel & Metals",
    embodiedCarbon: 2.12,
    unit: "kgCO2e/kg",
    density: 7850,
    notes: "Includes forming and coating",
    typicalApplications: "Roof and wall cladding for industrial/commercial",
  },
  {
    id: "stainless-steel",
    name: "Stainless Steel",
    category: "Steel & Metals",
    embodiedCarbon: 6.15,
    unit: "kgCO2e/kg",
    density: 8000,
    notes: "High chromium content - very high embodied carbon",
    typicalApplications: "Fixings, balustrades, cladding features, kitchen",
  },
  {
    id: "aluminium-general",
    name: "Aluminium (General)",
    category: "Steel & Metals",
    embodiedCarbon: 9.16,
    unit: "kgCO2e/kg",
    density: 2700,
    notes: "Virgin aluminium - very high embodied carbon",
    alternatives: ["aluminium-recycled"],
    typicalApplications: "Windows, curtain walling, cladding, rainscreen",
  },
  {
    id: "aluminium-recycled",
    name: "Recycled Aluminium",
    category: "Steel & Metals",
    embodiedCarbon: 1.69,
    unit: "kgCO2e/kg",
    density: 2700,
    notes: "83% lower carbon than virgin",
    fhsRecommended: true,
    typicalApplications: "Windows, curtain walling, cladding",
  },
  {
    id: "copper",
    name: "Copper",
    category: "Steel & Metals",
    embodiedCarbon: 3.81,
    unit: "kgCO2e/kg",
    density: 8940,
    typicalApplications: "Pipes, wiring, flashings, roofing",
  },
  {
    id: "zinc-sheet",
    name: "Zinc Sheet",
    category: "Steel & Metals",
    embodiedCarbon: 3.09,
    unit: "kgCO2e/kg",
    density: 7135,
    typicalApplications: "Roofing, cladding, flashings, rainwater goods",
  },
  {
    id: "lead-sheet",
    name: "Lead Sheet",
    category: "Steel & Metals",
    embodiedCarbon: 1.57,
    unit: "kgCO2e/kg",
    density: 11340,
    typicalApplications: "Flashings, flat roof details, heritage repairs",
  },
  {
    id: "cast-iron",
    name: "Cast Iron",
    category: "Steel & Metals",
    embodiedCarbon: 1.91,
    unit: "kgCO2e/kg",
    density: 7200,
    typicalApplications: "Drainage pipes, manhole covers, heritage features",
  },

  /* ═══════════════════════════════════════
     TIMBER & WOOD
     ═══════════════════════════════════════ */
  {
    id: "softwood-general",
    name: "Softwood (General)",
    category: "Timber & Wood",
    embodiedCarbon: 0.31,
    unit: "kgCO2e/kg",
    density: 510,
    notes: "Includes carbon sequestration credit",
    fhsRecommended: true,
    typicalApplications: "Studwork, roof trusses, joists, cladding",
  },
  {
    id: "hardwood-general",
    name: "Hardwood (General)",
    category: "Timber & Wood",
    embodiedCarbon: 0.43,
    unit: "kgCO2e/kg",
    density: 700,
    typicalApplications: "Flooring, joinery, external doors, decking",
  },
  {
    id: "glulam",
    name: "Glued Laminated Timber (Glulam)",
    category: "Timber & Wood",
    embodiedCarbon: 0.42,
    unit: "kgCO2e/kg",
    density: 500,
    notes: "Engineered timber - excellent steel alternative for beams and columns",
    fhsRecommended: true,
    typicalApplications: "Structural beams, columns, portal frames",
  },
  {
    id: "clt",
    name: "Cross-Laminated Timber (CLT)",
    category: "Timber & Wood",
    embodiedCarbon: 0.44,
    unit: "kgCO2e/kg",
    density: 480,
    notes: "Mass timber - rapidly growing in UK construction up to 10+ storeys",
    fhsRecommended: true,
    typicalApplications: "Structural walls, floors, roofs (alternative to concrete/steel frame)",
  },
  {
    id: "plywood",
    name: "Plywood",
    category: "Timber & Wood",
    embodiedCarbon: 0.65,
    unit: "kgCO2e/kg",
    density: 600,
    typicalApplications: "Sheathing, flooring substrate, formwork",
  },
  {
    id: "mdf",
    name: "MDF (Medium Density Fibreboard)",
    category: "Timber & Wood",
    embodiedCarbon: 0.59,
    unit: "kgCO2e/kg",
    density: 700,
    typicalApplications: "Internal joinery, skirting, cabinetry",
  },
  {
    id: "osb",
    name: "OSB (Oriented Strand Board)",
    category: "Timber & Wood",
    embodiedCarbon: 0.58,
    unit: "kgCO2e/kg",
    density: 630,
    notes: "Engineered sheet product from softwood strands",
    typicalApplications: "Wall sheathing, flooring decks, SIP panels",
  },
  {
    id: "particle-board",
    name: "Particle Board / Chipboard",
    category: "Timber & Wood",
    embodiedCarbon: 0.54,
    unit: "kgCO2e/kg",
    density: 680,
    typicalApplications: "Flooring substrate, furniture, partitions",
  },
  {
    id: "timber-cladding",
    name: "Timber Cladding (Treated Softwood)",
    category: "Timber & Wood",
    embodiedCarbon: 0.35,
    unit: "kgCO2e/kg",
    density: 520,
    notes: "Pressure-treated external cladding boards",
    fhsRecommended: true,
    typicalApplications: "External wall cladding, soffits, fascias",
  },
  {
    id: "timber-i-joist",
    name: "Timber I-Joist",
    category: "Timber & Wood",
    embodiedCarbon: 0.40,
    unit: "kgCO2e/kg",
    density: 480,
    notes: "Engineered joist - uses less material than solid timber",
    fhsRecommended: true,
    typicalApplications: "Floor joists, roof rafters",
  },
  {
    id: "cork",
    name: "Cork (Expanded)",
    category: "Timber & Wood",
    embodiedCarbon: 0.19,
    unit: "kgCO2e/kg",
    density: 120,
    notes: "Harvested from bark - regenerates without felling the tree",
    fhsRecommended: true,
    typicalApplications: "Insulation, underlay, wall finishes, expansion joints",
  },
  {
    id: "lvl",
    name: "Laminated Veneer Lumber (LVL)",
    category: "Timber & Wood",
    embodiedCarbon: 0.46,
    unit: "kgCO2e/kg",
    density: 510,
    notes: "Engineered structural timber with consistent properties",
    fhsRecommended: true,
    typicalApplications: "Beams, headers, studs, rim boards",
  },

  /* ═══════════════════════════════════════
     INSULATION
     ═══════════════════════════════════════ */
  {
    id: "mineral-wool",
    name: "Mineral Wool (Glass/Rock)",
    category: "Insulation",
    embodiedCarbon: 1.28,
    unit: "kgCO2e/kg",
    density: 30,
    notes: "Glass or rock wool insulation",
    alternatives: ["cellulose-insulation", "wood-fibre-insulation", "sheeps-wool", "hemp-insulation"],
    typicalApplications: "Cavity walls, loft, between studs, acoustic",
  },
  {
    id: "eps",
    name: "Expanded Polystyrene (EPS)",
    category: "Insulation",
    embodiedCarbon: 3.29,
    unit: "kgCO2e/kg",
    density: 20,
    alternatives: ["wood-fibre-insulation", "cellulose-insulation", "cork"],
    typicalApplications: "External wall insulation, below slab, flat roofs",
  },
  {
    id: "xps",
    name: "Extruded Polystyrene (XPS)",
    category: "Insulation",
    embodiedCarbon: 3.44,
    unit: "kgCO2e/kg",
    density: 35,
    alternatives: ["wood-fibre-insulation", "cellulose-insulation"],
    typicalApplications: "Below ground, inverted roofs, high-moisture areas",
  },
  {
    id: "pir",
    name: "PIR / PUR Foam Board",
    category: "Insulation",
    embodiedCarbon: 3.48,
    unit: "kgCO2e/kg",
    density: 32,
    notes: "Polyisocyanurate - high thermal performance but high carbon",
    alternatives: ["wood-fibre-insulation", "mineral-wool", "sheeps-wool"],
    typicalApplications: "Flat roofs, walls where thin build-up needed",
  },
  {
    id: "phenolic-foam",
    name: "Phenolic Foam Board",
    category: "Insulation",
    embodiedCarbon: 4.20,
    unit: "kgCO2e/kg",
    density: 35,
    notes: "Highest thermal performance per mm but very high embodied carbon",
    alternatives: ["wood-fibre-insulation", "cellulose-insulation"],
    typicalApplications: "Thin-wall build-ups, refurbishment, flat roofs",
  },
  {
    id: "spray-foam",
    name: "Spray Foam (Open Cell)",
    category: "Insulation",
    embodiedCarbon: 2.50,
    unit: "kgCO2e/kg",
    density: 10,
    notes: "Applied in-situ - fills irregular cavities but hard to remove",
    alternatives: ["cellulose-insulation", "sheeps-wool"],
    typicalApplications: "Retrofit cavity fill, loft spaces, irregular voids",
  },
  {
    id: "cellulose-insulation",
    name: "Cellulose Insulation",
    category: "Insulation",
    embodiedCarbon: 0.20,
    unit: "kgCO2e/kg",
    density: 45,
    notes: "Recycled newspaper - lowest carbon insulation option",
    fhsRecommended: true,
    typicalApplications: "Loft, timber frame cavities, retrofit",
  },
  {
    id: "wood-fibre-insulation",
    name: "Wood Fibre Insulation",
    category: "Insulation",
    embodiedCarbon: 0.45,
    unit: "kgCO2e/kg",
    density: 50,
    notes: "Natural fibre - carbon sequestration benefits",
    fhsRecommended: true,
    typicalApplications: "External walls, roof, breathable wall build-ups",
  },
  {
    id: "sheeps-wool",
    name: "Sheep's Wool Insulation",
    category: "Insulation",
    embodiedCarbon: 0.17,
    unit: "kgCO2e/kg",
    density: 25,
    notes: "Natural, breathable, and moisture-regulating insulation",
    fhsRecommended: true,
    typicalApplications: "Timber frame walls, loft, between rafters",
  },
  {
    id: "hemp-insulation",
    name: "Hemp Fibre Insulation",
    category: "Insulation",
    embodiedCarbon: 0.12,
    unit: "kgCO2e/kg",
    density: 40,
    notes: "Very low carbon with sequestration - fast-growing crop",
    fhsRecommended: true,
    typicalApplications: "Timber frame walls, loft, internal wall insulation",
  },
  {
    id: "aerogel-insulation",
    name: "Aerogel Insulation Blanket",
    category: "Insulation",
    embodiedCarbon: 5.00,
    unit: "kgCO2e/kg",
    density: 150,
    notes: "Ultra-thin, extremely high performance - suits constrained spaces",
    typicalApplications: "Heritage retrofit, thin walls, pipe insulation",
  },

  /* ═══════════════════════════════════════
     GLASS
     ═══════════════════════════════════════ */
  {
    id: "float-glass",
    name: "Float Glass (General)",
    category: "Glass",
    embodiedCarbon: 1.14,
    unit: "kgCO2e/kg",
    density: 2500,
    typicalApplications: "Base glass for further processing",
  },
  {
    id: "toughened-glass",
    name: "Toughened Glass",
    category: "Glass",
    embodiedCarbon: 1.27,
    unit: "kgCO2e/kg",
    density: 2500,
    typicalApplications: "Doors, screens, side panels, balustrades",
  },
  {
    id: "double-glazing",
    name: "Double Glazing Unit",
    category: "Glass",
    embodiedCarbon: 1.30,
    unit: "kgCO2e/kg",
    density: 2500,
    notes: "Includes spacer bar and sealant",
    alternatives: ["triple-glazing"],
    typicalApplications: "Windows, curtain walling, doors",
  },
  {
    id: "triple-glazing",
    name: "Triple Glazing Unit",
    category: "Glass",
    embodiedCarbon: 1.50,
    unit: "kgCO2e/kg",
    density: 2500,
    notes: "Higher embodied carbon but significantly better U-value - net benefit over building life",
    fhsRecommended: true,
    typicalApplications: "Passivhaus, high-performance windows, FHS-compliant homes",
  },
  {
    id: "laminated-glass",
    name: "Laminated Glass",
    category: "Glass",
    embodiedCarbon: 1.45,
    unit: "kgCO2e/kg",
    density: 2500,
    notes: "Two panes bonded with PVB interlayer for safety",
    typicalApplications: "Overhead glazing, rooflights, balustrades, acoustic",
  },
  {
    id: "low-e-glass",
    name: "Low-E Coated Glass",
    category: "Glass",
    embodiedCarbon: 1.35,
    unit: "kgCO2e/kg",
    density: 2500,
    notes: "Emissivity coating reduces heat loss - standard in modern glazing",
    fhsRecommended: true,
    typicalApplications: "Energy-efficient windows, curtain walling",
  },

  /* ═══════════════════════════════════════
     BRICKS & BLOCKS
     ═══════════════════════════════════════ */
  {
    id: "clay-brick",
    name: "Clay Brick (General)",
    category: "Bricks & Blocks",
    embodiedCarbon: 0.24,
    unit: "kgCO2e/kg",
    density: 1900,
    notes: "UK average fired clay brick",
    alternatives: ["calcium-silicate-brick", "concrete-block"],
    typicalApplications: "External walls, internal walls, features",
  },
  {
    id: "engineering-brick",
    name: "Engineering Brick",
    category: "Bricks & Blocks",
    embodiedCarbon: 0.30,
    unit: "kgCO2e/kg",
    density: 2200,
    notes: "High-strength, low porosity - fired at higher temperatures",
    alternatives: ["concrete-block"],
    typicalApplications: "DPC courses, manholes, retaining walls, foundations",
  },
  {
    id: "calcium-silicate-brick",
    name: "Calcium Silicate Brick",
    category: "Bricks & Blocks",
    embodiedCarbon: 0.12,
    unit: "kgCO2e/kg",
    density: 1850,
    notes: "Lime + sand - autoclaved, not kiln-fired. 50% less carbon than clay",
    fhsRecommended: true,
    typicalApplications: "External and internal walls, load-bearing masonry",
  },
  {
    id: "concrete-block",
    name: "Concrete Block (Dense)",
    category: "Bricks & Blocks",
    embodiedCarbon: 0.094,
    unit: "kgCO2e/kg",
    density: 2000,
    typicalApplications: "Internal walls, foundations, below-ground",
  },
  {
    id: "concrete-block-lightweight",
    name: "Concrete Block (Lightweight)",
    category: "Bricks & Blocks",
    embodiedCarbon: 0.120,
    unit: "kgCO2e/kg",
    density: 1400,
    notes: "Aerated or aggregate-lightweight - better thermal performance",
    typicalApplications: "Inner leaf of cavity walls, partitions",
  },
  {
    id: "aac-block",
    name: "Autoclaved Aerated Concrete (AAC)",
    category: "Bricks & Blocks",
    embodiedCarbon: 0.30,
    unit: "kgCO2e/kg",
    density: 600,
    notes: "Lightweight - less material per m² of wall",
    typicalApplications: "Inner leaf walls, partitions, upper storeys",
  },
  {
    id: "natural-stone-limestone",
    name: "Natural Stone (Limestone)",
    category: "Bricks & Blocks",
    embodiedCarbon: 0.09,
    unit: "kgCO2e/kg",
    density: 2180,
    notes: "Quarried and cut - minimal processing energy",
    fhsRecommended: true,
    typicalApplications: "Cladding, walling, paving, restoration",
  },
  {
    id: "natural-stone-granite",
    name: "Natural Stone (Granite)",
    category: "Bricks & Blocks",
    embodiedCarbon: 0.70,
    unit: "kgCO2e/kg",
    density: 2650,
    notes: "Hard stone - requires significant cutting and polishing energy",
    typicalApplications: "Cladding, paving, worktops, kerbs",
  },
  {
    id: "rammed-earth",
    name: "Rammed Earth",
    category: "Bricks & Blocks",
    embodiedCarbon: 0.024,
    unit: "kgCO2e/kg",
    density: 1900,
    notes: "Compacted local subsoil - ultra-low embodied carbon",
    fhsRecommended: true,
    typicalApplications: "Feature walls, residential, low-rise structures",
  },

  /* ═══════════════════════════════════════
     PLASTICS & POLYMERS
     ═══════════════════════════════════════ */
  {
    id: "pvc",
    name: "PVC (Polyvinyl Chloride)",
    category: "Plastics & Polymers",
    embodiedCarbon: 3.10,
    unit: "kgCO2e/kg",
    density: 1380,
    notes: "Used in pipes, windows, cladding",
    typicalApplications: "Windows, rainwater goods, pipes, flooring",
  },
  {
    id: "hdpe",
    name: "HDPE (High-Density Polyethylene)",
    category: "Plastics & Polymers",
    embodiedCarbon: 1.93,
    unit: "kgCO2e/kg",
    density: 960,
    notes: "Used in drainage, damp proof membranes",
    typicalApplications: "Drainage pipes, DPMs, gas membranes",
  },
  {
    id: "polypropylene",
    name: "Polypropylene (PP)",
    category: "Plastics & Polymers",
    embodiedCarbon: 3.43,
    unit: "kgCO2e/kg",
    density: 900,
    typicalApplications: "Drainage, geotextiles, carpet fibre, fittings",
  },
  {
    id: "epdm",
    name: "EPDM Rubber",
    category: "Plastics & Polymers",
    embodiedCarbon: 3.50,
    unit: "kgCO2e/kg",
    density: 1150,
    typicalApplications: "Flat roof membranes, gaskets, seals",
  },
  {
    id: "polycarbonate",
    name: "Polycarbonate Sheet",
    category: "Plastics & Polymers",
    embodiedCarbon: 7.62,
    unit: "kgCO2e/kg",
    density: 1200,
    notes: "Very high embodied carbon - lightweight glazing alternative",
    typicalApplications: "Rooflights, canopies, atria, sports facilities",
  },
  {
    id: "grp",
    name: "GRP (Glass Reinforced Plastic)",
    category: "Plastics & Polymers",
    embodiedCarbon: 6.90,
    unit: "kgCO2e/kg",
    density: 1600,
    typicalApplications: "Cladding panels, dormers, bay windows, tanks",
  },
  {
    id: "nylon",
    name: "Nylon / Polyamide",
    category: "Plastics & Polymers",
    embodiedCarbon: 8.10,
    unit: "kgCO2e/kg",
    density: 1140,
    notes: "Very high embodied carbon - used in small quantities",
    typicalApplications: "Fixings, wall ties, carpet fibres, membranes",
  },
  {
    id: "silicone-sealant",
    name: "Silicone Sealant",
    category: "Plastics & Polymers",
    embodiedCarbon: 4.70,
    unit: "kgCO2e/kg",
    density: 1200,
    typicalApplications: "Glazing seals, joint sealant, waterproofing",
  },

  /* ═══════════════════════════════════════
     AGGREGATES
     ═══════════════════════════════════════ */
  {
    id: "aggregate-natural",
    name: "Natural Aggregate (Gravel)",
    category: "Aggregates",
    embodiedCarbon: 0.0048,
    unit: "kgCO2e/kg",
    density: 1520,
    typicalApplications: "Concrete mix, sub-base, drainage, landscaping",
  },
  {
    id: "aggregate-recycled",
    name: "Recycled Aggregate",
    category: "Aggregates",
    embodiedCarbon: 0.0046,
    unit: "kgCO2e/kg",
    density: 1400,
    notes: "Crushed demolition concrete",
    fhsRecommended: true,
    typicalApplications: "Sub-base, fill, non-structural concrete",
  },
  {
    id: "sand",
    name: "Sand",
    category: "Aggregates",
    embodiedCarbon: 0.0051,
    unit: "kgCO2e/kg",
    density: 1600,
    typicalApplications: "Concrete, mortar, render, bedding",
  },
  {
    id: "limestone-aggregate",
    name: "Limestone (Crushed)",
    category: "Aggregates",
    embodiedCarbon: 0.017,
    unit: "kgCO2e/kg",
    density: 1550,
    typicalApplications: "Decorative aggregate, sub-base, fill",
  },
  {
    id: "hardcore",
    name: "Hardcore (Site-Won)",
    category: "Aggregates",
    embodiedCarbon: 0.0024,
    unit: "kgCO2e/kg",
    density: 1900,
    notes: "Re-used demolition material - lowest impact aggregate",
    fhsRecommended: true,
    typicalApplications: "Sub-base, fill, ground works",
  },

  /* ═══════════════════════════════════════
     PLASTER & RENDER
     ═══════════════════════════════════════ */
  {
    id: "plasterboard",
    name: "Plasterboard (Standard)",
    category: "Plaster & Render",
    embodiedCarbon: 0.39,
    unit: "kgCO2e/kg",
    density: 800,
    typicalApplications: "Wall and ceiling linings, partitions, drylining",
  },
  {
    id: "plasterboard-fire",
    name: "Plasterboard (Fire-Rated)",
    category: "Plaster & Render",
    embodiedCarbon: 0.42,
    unit: "kgCO2e/kg",
    density: 900,
    notes: "Glass fibre reinforced for fire resistance",
    typicalApplications: "Fire compartment walls, ceilings, party walls",
  },
  {
    id: "gypsum-plaster",
    name: "Gypsum Plaster",
    category: "Plaster & Render",
    embodiedCarbon: 0.33,
    unit: "kgCO2e/kg",
    density: 1300,
    typicalApplications: "Internal wall and ceiling skim coat",
  },
  {
    id: "cement-render",
    name: "Cement Render",
    category: "Plaster & Render",
    embodiedCarbon: 0.12,
    unit: "kgCO2e/kg",
    density: 1800,
    alternatives: ["lime-render", "clay-plaster"],
    typicalApplications: "External wall render, base coat for EWI systems",
  },
  {
    id: "lime-render",
    name: "Lime Render",
    category: "Plaster & Render",
    embodiedCarbon: 0.074,
    unit: "kgCO2e/kg",
    density: 1600,
    notes: "Lower carbon alternative to cement render - breathable finish",
    fhsRecommended: true,
    typicalApplications: "External walls, heritage buildings, breathable build-ups",
  },
  {
    id: "lime-plaster",
    name: "Lime Plaster",
    category: "Plaster & Render",
    embodiedCarbon: 0.065,
    unit: "kgCO2e/kg",
    density: 1400,
    notes: "Reabsorbs CO₂ during curing (carbonation)",
    fhsRecommended: true,
    typicalApplications: "Internal walls, heritage restoration, eco-builds",
  },
  {
    id: "clay-plaster",
    name: "Clay Plaster",
    category: "Plaster & Render",
    embodiedCarbon: 0.02,
    unit: "kgCO2e/kg",
    density: 1500,
    notes: "Earth-based - ultra-low carbon, moisture-regulating",
    fhsRecommended: true,
    typicalApplications: "Internal feature walls, eco-builds, heritage",
  },

  /* ═══════════════════════════════════════
     ROOFING
     ═══════════════════════════════════════ */
  {
    id: "clay-tile",
    name: "Clay Roof Tile",
    category: "Roofing",
    embodiedCarbon: 0.45,
    unit: "kgCO2e/kg",
    density: 1900,
    alternatives: ["concrete-tile", "slate"],
    typicalApplications: "Pitched roof covering, residential",
  },
  {
    id: "concrete-tile",
    name: "Concrete Roof Tile",
    category: "Roofing",
    embodiedCarbon: 0.18,
    unit: "kgCO2e/kg",
    density: 2100,
    typicalApplications: "Pitched roof covering, residential, commercial",
  },
  {
    id: "slate",
    name: "Natural Slate",
    category: "Roofing",
    embodiedCarbon: 0.058,
    unit: "kgCO2e/kg",
    density: 2700,
    notes: "Quarried stone - very low processing energy, long lifespan",
    fhsRecommended: true,
    typicalApplications: "Pitched roof covering, feature roofing",
  },
  {
    id: "fibre-cement-slate",
    name: "Fibre Cement Slate",
    category: "Roofing",
    embodiedCarbon: 0.47,
    unit: "kgCO2e/kg",
    density: 1700,
    notes: "Cement-based manufactured slate - lighter than natural",
    typicalApplications: "Pitched roof covering, cladding, soffits",
  },
  {
    id: "bitumen-felt",
    name: "Bitumen Roofing Felt",
    category: "Roofing",
    embodiedCarbon: 0.49,
    unit: "kgCO2e/kg",
    density: 1100,
    notes: "ICE v4.1 updated to 0.49 from 0.44 based on latest Eurobitume LCA data.",
    typicalApplications: "Flat roof membranes, underlay, garden buildings",
  },
  {
    id: "zinc-roofing",
    name: "Zinc Standing Seam Roofing",
    category: "Roofing",
    embodiedCarbon: 3.09,
    unit: "kgCO2e/kg",
    density: 7135,
    notes: "Premium metal roofing - very long lifespan (80+ years)",
    typicalApplications: "Feature roofing, cladding, dormers, extensions",
  },
  {
    id: "epdm-roof-membrane",
    name: "EPDM Flat Roof Membrane",
    category: "Roofing",
    embodiedCarbon: 3.50,
    unit: "kgCO2e/kg",
    density: 1150,
    notes: "Synthetic rubber - long life, single-ply membrane",
    typicalApplications: "Flat roofs, green roof base, garden rooms",
  },
  {
    id: "green-roof-substrate",
    name: "Green Roof Substrate",
    category: "Roofing",
    embodiedCarbon: 0.12,
    unit: "kgCO2e/kg",
    density: 800,
    notes: "Growing medium for extensive/intensive green roofs - biodiversity benefits",
    fhsRecommended: true,
    typicalApplications: "Green roofs, blue-green infrastructure, biodiversity roofs",
  },

  /* ═══════════════════════════════════════
     FLOORING
     ═══════════════════════════════════════ */
  {
    id: "ceramic-tile",
    name: "Ceramic Floor Tile",
    category: "Flooring",
    embodiedCarbon: 0.78,
    unit: "kgCO2e/kg",
    density: 2000,
    typicalApplications: "Bathrooms, kitchens, commercial floors",
  },
  {
    id: "porcelain-tile",
    name: "Porcelain Tile",
    category: "Flooring",
    embodiedCarbon: 1.12,
    unit: "kgCO2e/kg",
    density: 2300,
    notes: "Fired at higher temperature than ceramic - harder and denser",
    alternatives: ["ceramic-tile", "terrazzo", "natural-stone-floor"],
    typicalApplications: "High-traffic floors, external paving, commercial",
  },
  {
    id: "vinyl-lvt",
    name: "Luxury Vinyl Tile (LVT)",
    category: "Flooring",
    embodiedCarbon: 2.81,
    unit: "kgCO2e/kg",
    density: 1600,
    alternatives: ["linoleum", "natural-stone-floor"],
    typicalApplications: "Residential, retail, healthcare, hospitality",
  },
  {
    id: "carpet-synthetic",
    name: "Carpet (Synthetic)",
    category: "Flooring",
    embodiedCarbon: 3.89,
    unit: "kgCO2e/kg",
    density: 320,
    notes: "Nylon/polypropylene pile - high embodied carbon, short lifespan",
    alternatives: ["carpet-wool", "linoleum"],
    typicalApplications: "Offices, residential, hospitality",
  },
  {
    id: "carpet-wool",
    name: "Carpet (Wool)",
    category: "Flooring",
    embodiedCarbon: 1.80,
    unit: "kgCO2e/kg",
    density: 350,
    notes: "Natural fibre - 54% less carbon than synthetic",
    fhsRecommended: true,
    typicalApplications: "Residential, premium commercial",
  },
  {
    id: "terrazzo",
    name: "Terrazzo (In-Situ)",
    category: "Flooring",
    embodiedCarbon: 0.15,
    unit: "kgCO2e/kg",
    density: 2400,
    notes: "Composite of marble/granite chips in cement - very durable",
    typicalApplications: "Lobbies, corridors, commercial, heritage restoration",
  },
  {
    id: "linoleum",
    name: "Linoleum",
    category: "Flooring",
    embodiedCarbon: 1.21,
    unit: "kgCO2e/kg",
    density: 1200,
    notes: "Made from linseed oil, cork, and wood flour - natural product",
    fhsRecommended: true,
    typicalApplications: "Healthcare, education, retail, residential",
  },
  {
    id: "natural-stone-floor",
    name: "Natural Stone Floor (Limestone/Sandstone)",
    category: "Flooring",
    embodiedCarbon: 0.09,
    unit: "kgCO2e/kg",
    density: 2200,
    notes: "Quarried and cut - minimal processing, very long lifespan",
    fhsRecommended: true,
    typicalApplications: "Entrance lobbies, kitchens, heritage, commercial",
  },
  {
    id: "rubber-flooring",
    name: "Rubber Flooring",
    category: "Flooring",
    embodiedCarbon: 2.42,
    unit: "kgCO2e/kg",
    density: 1500,
    typicalApplications: "Sports facilities, playgrounds, gyms, commercial",
  },

  /* ═══════════════════════════════════════
     WATERPROOFING & MEMBRANES
     ═══════════════════════════════════════ */
  {
    id: "bitumen-dpm",
    name: "Bitumen DPM / Tanking",
    category: "Waterproofing & Membranes",
    embodiedCarbon: 0.49,
    unit: "kgCO2e/kg",
    density: 1100,
    notes: "ICE v4.1 updated to 0.49 from 0.44 based on latest Eurobitume LCA data.",
    typicalApplications: "Below-ground tanking, damp proof membranes",
  },
  {
    id: "polyethylene-dpm",
    name: "Polyethylene DPM (1200g)",
    category: "Waterproofing & Membranes",
    embodiedCarbon: 1.93,
    unit: "kgCO2e/kg",
    density: 940,
    typicalApplications: "Below-slab DPM, damp proof course, gas membrane",
  },
  {
    id: "tpo-membrane",
    name: "TPO Single-Ply Membrane",
    category: "Waterproofing & Membranes",
    embodiedCarbon: 2.80,
    unit: "kgCO2e/kg",
    density: 1200,
    notes: "Thermoplastic polyolefin - weldable, recyclable",
    typicalApplications: "Flat roof waterproofing, podium decks",
  },
  {
    id: "liquid-waterproofing",
    name: "Liquid Applied Waterproofing",
    category: "Waterproofing & Membranes",
    embodiedCarbon: 3.20,
    unit: "kgCO2e/kg",
    density: 1300,
    typicalApplications: "Complex roof details, balconies, walkways",
  },
  {
    id: "breather-membrane",
    name: "Breather Membrane (Vapour Permeable)",
    category: "Waterproofing & Membranes",
    embodiedCarbon: 2.50,
    unit: "kgCO2e/kg",
    density: 80,
    notes: "Allows moisture vapour to pass while blocking liquid water",
    typicalApplications: "Behind cladding, under roof tiles, timber frame walls",
  },
  {
    id: "vcl",
    name: "Vapour Control Layer (Polythene)",
    category: "Waterproofing & Membranes",
    embodiedCarbon: 1.93,
    unit: "kgCO2e/kg",
    density: 940,
    typicalApplications: "Warm-side of insulation in walls, roofs, floors",
  },

  /* ═══════════════════════════════════════
     ADHESIVES & SEALANTS
     ═══════════════════════════════════════ */
  {
    id: "epoxy-adhesive",
    name: "Epoxy Adhesive",
    category: "Adhesives & Sealants",
    embodiedCarbon: 6.50,
    unit: "kgCO2e/kg",
    density: 1200,
    notes: "Two-part structural adhesive - very high embodied carbon",
    typicalApplications: "Structural bonding, FRP fixing, anchoring",
  },
  {
    id: "polyurethane-adhesive",
    name: "Polyurethane Adhesive",
    category: "Adhesives & Sealants",
    embodiedCarbon: 4.20,
    unit: "kgCO2e/kg",
    density: 1100,
    typicalApplications: "Floor bonding, insulation fixing, timber laminating",
  },
  {
    id: "pva-adhesive",
    name: "PVA Wood Adhesive",
    category: "Adhesives & Sealants",
    embodiedCarbon: 1.80,
    unit: "kgCO2e/kg",
    density: 1050,
    typicalApplications: "Internal joinery, carpentry, woodwork",
  },
  {
    id: "tile-adhesive",
    name: "Tile Adhesive (Cement-Based)",
    category: "Adhesives & Sealants",
    embodiedCarbon: 0.67,
    unit: "kgCO2e/kg",
    density: 1600,
    typicalApplications: "Wall and floor tiling, external cladding fixing",
  },
  {
    id: "polysulphide-sealant",
    name: "Polysulphide Sealant",
    category: "Adhesives & Sealants",
    embodiedCarbon: 3.90,
    unit: "kgCO2e/kg",
    density: 1400,
    typicalApplications: "Movement joints, curtain walling, glazing",
  },
  {
    id: "mastic-sealant",
    name: "Mastic Asphalt Sealant",
    category: "Adhesives & Sealants",
    embodiedCarbon: 0.49,
    unit: "kgCO2e/kg",
    density: 2300,
    notes: "ICE v4.1 bitumen-based value",
    typicalApplications: "Flat roof details, tanking, paving joints",
  },
  {
    id: "mortar-general",
    name: "Mortar (Cement:Sand 1:4)",
    category: "Adhesives & Sealants",
    embodiedCarbon: 0.163,
    unit: "kgCO2e/kg",
    density: 1900,
    alternatives: ["lime-mortar"],
    typicalApplications: "Bricklaying, blockwork, pointing",
  },
  {
    id: "lime-mortar",
    name: "Lime Mortar (NHL)",
    category: "Adhesives & Sealants",
    embodiedCarbon: 0.082,
    unit: "kgCO2e/kg",
    density: 1700,
    notes: "Natural hydraulic lime - 50% less carbon than cement mortar, breathable",
    fhsRecommended: true,
    typicalApplications: "Heritage, conservation, breathable masonry",
  },

  /* ═══════════════════════════════════════
     PAINTS & COATINGS
     ═══════════════════════════════════════ */
  {
    id: "paint-water-based",
    name: "Water-Based Emulsion Paint",
    category: "Paints & Coatings",
    embodiedCarbon: 2.10,
    unit: "kgCO2e/kg",
    density: 1300,
    typicalApplications: "Internal walls, ceilings",
  },
  {
    id: "paint-solvent-based",
    name: "Solvent-Based Paint / Gloss",
    category: "Paints & Coatings",
    embodiedCarbon: 3.56,
    unit: "kgCO2e/kg",
    density: 1200,
    notes: "Higher VOC and higher embodied carbon than water-based",
    alternatives: ["paint-water-based"],
    typicalApplications: "External woodwork, metalwork, trim",
  },
  {
    id: "powder-coating",
    name: "Powder Coating (Polyester)",
    category: "Paints & Coatings",
    embodiedCarbon: 5.20,
    unit: "kgCO2e/kg",
    density: 1300,
    typicalApplications: "Metal cladding, window frames, railings",
  },
  {
    id: "intumescent-paint",
    name: "Intumescent Fire Paint",
    category: "Paints & Coatings",
    embodiedCarbon: 4.80,
    unit: "kgCO2e/kg",
    density: 1350,
    typicalApplications: "Structural steel fire protection",
  },
  {
    id: "linseed-paint",
    name: "Linseed Oil Paint",
    category: "Paints & Coatings",
    embodiedCarbon: 0.90,
    unit: "kgCO2e/kg",
    density: 950,
    notes: "Bio-based - significantly lower carbon than petrochemical paints",
    fhsRecommended: true,
    typicalApplications: "External timber, heritage, eco-builds",
  },
  {
    id: "galvanising-hot-dip",
    name: "Hot-Dip Galvanising",
    category: "Paints & Coatings",
    embodiedCarbon: 1.20,
    unit: "kgCO2e/kg",
    density: 7135,
    notes: "Zinc coating for corrosion protection - extends steel life 50+ years",
    typicalApplications: "Structural steel, lintels, purlins, external fixings",
  },
  {
    id: "anodising",
    name: "Anodised Aluminium Finish",
    category: "Paints & Coatings",
    embodiedCarbon: 8.50,
    unit: "kgCO2e/kg",
    density: 2700,
    notes: "Electrochemical process - adds to aluminium's already high embodied carbon",
    typicalApplications: "Curtain walling, window frames, architectural features",
  },

  /* ═══════════════════════════════════════
     PIPES & DRAINAGE
     ═══════════════════════════════════════ */
  {
    id: "clay-pipe",
    name: "Vitrified Clay Drainage Pipe",
    category: "Pipes & Drainage",
    embodiedCarbon: 0.46,
    unit: "kgCO2e/kg",
    density: 2100,
    notes: "Fired clay - durable, chemically resistant, 100+ year lifespan",
    typicalApplications: "Below-ground foul drainage, combined sewers",
  },
  {
    id: "concrete-pipe",
    name: "Concrete Drainage Pipe",
    category: "Pipes & Drainage",
    embodiedCarbon: 0.16,
    unit: "kgCO2e/kg",
    density: 2400,
    typicalApplications: "Surface water drainage, culverts, attenuation",
  },
  {
    id: "pvc-pipe",
    name: "PVC-U Drainage Pipe",
    category: "Pipes & Drainage",
    embodiedCarbon: 3.10,
    unit: "kgCO2e/kg",
    density: 1380,
    alternatives: ["clay-pipe", "concrete-pipe", "pe-pipe"],
    typicalApplications: "Below-ground drainage, soil stacks, waste pipes",
  },
  {
    id: "pe-pipe",
    name: "Polyethylene Pipe (PE100)",
    category: "Pipes & Drainage",
    embodiedCarbon: 2.52,
    unit: "kgCO2e/kg",
    density: 960,
    typicalApplications: "Water mains, gas supply, ground source heat pump loops",
  },
  {
    id: "copper-pipe",
    name: "Copper Pipe",
    category: "Pipes & Drainage",
    embodiedCarbon: 3.81,
    unit: "kgCO2e/kg",
    density: 8940,
    alternatives: ["mlc-pipe"],
    typicalApplications: "Hot/cold water, heating, refrigerant lines",
  },
  {
    id: "mlc-pipe",
    name: "Multi-Layer Composite Pipe (MLC)",
    category: "Pipes & Drainage",
    embodiedCarbon: 2.20,
    unit: "kgCO2e/kg",
    density: 1200,
    notes: "PE-Al-PE - lower carbon alternative to copper for heating/plumbing",
    fhsRecommended: true,
    typicalApplications: "Underfloor heating, plumbing, radiator connections",
  },
  {
    id: "ductile-iron-pipe",
    name: "Ductile Iron Pipe",
    category: "Pipes & Drainage",
    embodiedCarbon: 1.91,
    unit: "kgCO2e/kg",
    density: 7200,
    typicalApplications: "Water mains, fire hydrants, large-diameter drainage",
  },
  {
    id: "pp-pipe",
    name: "Polypropylene Pipe (PP-R)",
    category: "Pipes & Drainage",
    embodiedCarbon: 3.43,
    unit: "kgCO2e/kg",
    density: 900,
    typicalApplications: "Hot water systems, chemical drainage, MVHR ducting",
  },
  {
    id: "abs-pipe",
    name: "ABS Drainage Pipe",
    category: "Pipes & Drainage",
    embodiedCarbon: 3.50,
    unit: "kgCO2e/kg",
    density: 1050,
    typicalApplications: "Waste pipes, soil stacks, vents",
  },

  /* ═══════════════════════════════════════
     MEP & SERVICES
     ═══════════════════════════════════════ */
  {
    id: "copper-cable",
    name: "Copper Electrical Cable",
    category: "MEP & Services",
    embodiedCarbon: 4.20,
    unit: "kgCO2e/kg",
    density: 3500,
    notes: "Includes PVC insulation sheath",
    typicalApplications: "Power distribution, lighting, data",
  },
  {
    id: "steel-cable-tray",
    name: "Steel Cable Tray / Basket",
    category: "MEP & Services",
    embodiedCarbon: 1.55,
    unit: "kgCO2e/kg",
    density: 7850,
    typicalApplications: "Cable management, risers, plant rooms",
  },
  {
    id: "galvanised-ductwork",
    name: "Galvanised Steel Ductwork",
    category: "MEP & Services",
    embodiedCarbon: 1.62,
    unit: "kgCO2e/kg",
    density: 7850,
    typicalApplications: "HVAC distribution, ventilation, extract systems",
  },
  {
    id: "radiator-steel",
    name: "Steel Panel Radiator",
    category: "MEP & Services",
    embodiedCarbon: 1.55,
    unit: "kgCO2e/kg",
    density: 7850,
    typicalApplications: "Heating distribution, residential, commercial",
  },
  {
    id: "heat-pump-unit",
    name: "Air Source Heat Pump (unit)",
    category: "MEP & Services",
    embodiedCarbon: 3.80,
    unit: "kgCO2e/kg",
    density: 500,
    notes: "Approximate - varies significantly by manufacturer and capacity. FHS mandates low-carbon heating.",
    fhsRecommended: true,
    typicalApplications: "Space heating, hot water, FHS-compliant homes",
  },
  {
    id: "pv-panel",
    name: "Photovoltaic Panel (Crystalline Si)",
    category: "MEP & Services",
    embodiedCarbon: 4.10,
    unit: "kgCO2e/kg",
    density: 250,
    notes: "High upfront carbon but typically pays back within 2-4 years of operation",
    fhsRecommended: true,
    typicalApplications: "Roof-mounted solar, building-integrated PV",
  },
  {
    id: "led-luminaire",
    name: "LED Luminaire (General)",
    category: "MEP & Services",
    embodiedCarbon: 5.50,
    unit: "kgCO2e/kg",
    density: 800,
    notes: "Varies widely - includes housing, driver, and LED module",
    typicalApplications: "General lighting, commercial, residential",
  },
  {
    id: "mvhr-unit",
    name: "MVHR Unit (Mechanical Ventilation)",
    category: "MEP & Services",
    embodiedCarbon: 4.50,
    unit: "kgCO2e/kg",
    density: 600,
    notes: "Essential for airtight FHS-compliant buildings",
    fhsRecommended: true,
    typicalApplications: "Whole-house ventilation, Passivhaus, FHS homes",
  },
  {
    id: "underfloor-heating",
    name: "Underfloor Heating (Water System)",
    category: "MEP & Services",
    embodiedCarbon: 2.40,
    unit: "kgCO2e/kg",
    density: 1100,
    notes: "PE-X pipes in screed - efficient with heat pumps due to low flow temperatures",
    fhsRecommended: true,
    typicalApplications: "Residential, commercial, heat pump systems",
  },

  /* ═══════════════════════════════════════
     FIXINGS & CONNECTIONS
     ═══════════════════════════════════════ */
  {
    id: "stainless-fixings",
    name: "Stainless Steel Fixings",
    category: "Fixings & Connections",
    embodiedCarbon: 6.15,
    unit: "kgCO2e/kg",
    density: 8000,
    typicalApplications: "External cladding fixings, balustrades, marine",
  },
  {
    id: "galvanised-fixings",
    name: "Galvanised Mild Steel Fixings",
    category: "Fixings & Connections",
    embodiedCarbon: 1.62,
    unit: "kgCO2e/kg",
    density: 7850,
    typicalApplications: "General construction fixings, brackets, angles",
  },
  {
    id: "wall-ties",
    name: "Stainless Steel Wall Ties",
    category: "Fixings & Connections",
    embodiedCarbon: 6.15,
    unit: "kgCO2e/kg",
    density: 8000,
    typicalApplications: "Cavity wall construction, inner/outer leaf connection",
  },
  {
    id: "basalt-wall-ties",
    name: "Basalt Fibre Wall Ties",
    category: "Fixings & Connections",
    embodiedCarbon: 0.52,
    unit: "kgCO2e/kg",
    density: 1800,
    notes: "Low-carbon alternative to stainless steel - 92% less embodied carbon",
    fhsRecommended: true,
    typicalApplications: "Cavity wall construction, thermal bridge reduction",
  },
  {
    id: "resin-anchor",
    name: "Chemical Resin Anchor",
    category: "Fixings & Connections",
    embodiedCarbon: 5.80,
    unit: "kgCO2e/kg",
    density: 1400,
    typicalApplications: "Post-fixed connections to concrete, masonry",
  },
  {
    id: "timber-connector",
    name: "Timber Connector Plate (Galvanised)",
    category: "Fixings & Connections",
    embodiedCarbon: 1.62,
    unit: "kgCO2e/kg",
    density: 7850,
    typicalApplications: "Truss joints, joist hangers, timber frame connections",
  },

  /* ═══════════════════════════════════════
     ASPHALT & BITUMINOUS
     ═══════════════════════════════════════ */
  {
    id: "asphalt-road",
    name: "Asphalt (Road Surface)",
    category: "Asphalt & Bituminous",
    embodiedCarbon: 0.066,
    unit: "kgCO2e/kg",
    density: 2300,
    notes: "ICE v4.1 updated with latest Eurobitume data",
    alternatives: ["recycled-asphalt"],
    typicalApplications: "Road surfacing, car parks, hard standings",
  },
  {
    id: "recycled-asphalt",
    name: "Recycled Asphalt (RAP Mix)",
    category: "Asphalt & Bituminous",
    embodiedCarbon: 0.045,
    unit: "kgCO2e/kg",
    density: 2250,
    notes: "Reclaimed asphalt planings blended into new mix - ~30% carbon saving",
    fhsRecommended: true,
    typicalApplications: "Road resurfacing, car parks, base courses",
  },
  {
    id: "warm-mix-asphalt",
    name: "Warm Mix Asphalt",
    category: "Asphalt & Bituminous",
    embodiedCarbon: 0.055,
    unit: "kgCO2e/kg",
    density: 2300,
    notes: "Mixed at lower temperatures - ~15% energy saving over hot mix",
    fhsRecommended: true,
    typicalApplications: "Road surfacing, urban works, night works",
  },
  {
    id: "mastic-asphalt",
    name: "Mastic Asphalt",
    category: "Asphalt & Bituminous",
    embodiedCarbon: 0.49,
    unit: "kgCO2e/kg",
    density: 2300,
    notes: "ICE v4.1 Eurobitume value",
    typicalApplications: "Flat roof waterproofing, tanking, flooring",
  },

  /* ═══════════════════════════════════════
     GEOTEXTILES & GROUND
     ═══════════════════════════════════════ */
  {
    id: "geotextile-pp",
    name: "Geotextile (Polypropylene)",
    category: "Geotextiles & Ground",
    embodiedCarbon: 3.43,
    unit: "kgCO2e/kg",
    density: 200,
    typicalApplications: "Separation, filtration, drainage, green roofs",
  },
  {
    id: "geogrid-hdpe",
    name: "Geogrid (HDPE)",
    category: "Geotextiles & Ground",
    embodiedCarbon: 1.93,
    unit: "kgCO2e/kg",
    density: 300,
    typicalApplications: "Ground reinforcement, retaining walls, slopes",
  },
  {
    id: "geocellular-crate",
    name: "Geocellular Attenuation Crate",
    category: "Geotextiles & Ground",
    embodiedCarbon: 3.43,
    unit: "kgCO2e/kg",
    density: 50,
    notes: "PP modular crates - essential for SuDS compliance",
    typicalApplications: "Stormwater attenuation, soakaways, SuDS",
  },
  {
    id: "bentonite-waterproofing",
    name: "Bentonite Waterproofing Mat",
    category: "Geotextiles & Ground",
    embodiedCarbon: 0.08,
    unit: "kgCO2e/kg",
    density: 1200,
    notes: "Natural clay mineral - self-healing, very low embodied carbon",
    fhsRecommended: true,
    typicalApplications: "Below-ground waterproofing, basement tanking, ponds",
  },
  {
    id: "gabion-basket",
    name: "Gabion Basket (Galvanised Wire)",
    category: "Geotextiles & Ground",
    embodiedCarbon: 1.62,
    unit: "kgCO2e/kg",
    density: 7850,
    notes: "Wire basket only - fill with local stone for low overall carbon",
    typicalApplications: "Retaining walls, erosion control, landscape features",
  },

  /* ═══════════════════════════════════════
     FIRE PROTECTION
     ═══════════════════════════════════════ */
  {
    id: "fire-board-calcium",
    name: "Calcium Silicate Fire Board",
    category: "Fire Protection",
    embodiedCarbon: 1.60,
    unit: "kgCO2e/kg",
    density: 870,
    typicalApplications: "Steel fire protection, fire compartment walls, ducts",
  },
  {
    id: "fire-board-vermiculite",
    name: "Vermiculite Fire Board",
    category: "Fire Protection",
    embodiedCarbon: 1.20,
    unit: "kgCO2e/kg",
    density: 600,
    typicalApplications: "Steel encasement, ceiling fire barriers",
  },
  {
    id: "fire-spray-vermiculite",
    name: "Sprayed Vermiculite/Cement",
    category: "Fire Protection",
    embodiedCarbon: 0.85,
    unit: "kgCO2e/kg",
    density: 550,
    notes: "Lower carbon option for large-area steel fire protection",
    typicalApplications: "Steel frame fire protection, deck soffits",
  },
  {
    id: "fire-stop-sealant",
    name: "Fire Stop Sealant (Intumescent)",
    category: "Fire Protection",
    embodiedCarbon: 4.80,
    unit: "kgCO2e/kg",
    density: 1400,
    typicalApplications: "Service penetrations, compartment wall sealing",
  },
  {
    id: "fire-collar",
    name: "Intumescent Fire Collar",
    category: "Fire Protection",
    embodiedCarbon: 3.50,
    unit: "kgCO2e/kg",
    density: 2000,
    typicalApplications: "Pipe penetrations through fire compartment walls/floors",
  },
  {
    id: "rockwool-fire-batt",
    name: "Rockwool Fire Batt",
    category: "Fire Protection",
    embodiedCarbon: 1.28,
    unit: "kgCO2e/kg",
    density: 60,
    typicalApplications: "Fire stopping at party walls, floor junctions, voids",
  },

  /* ═══════════════════════════════════════
     ADDITIONAL CONCRETE & CEMENT (v4.1)
     ═══════════════════════════════════════ */
  {
    id: "geopolymer-concrete",
    name: "Geopolymer Concrete",
    category: "Concrete & Cement",
    embodiedCarbon: 0.055,
    unit: "kgCO2e/kg",
    density: 2350,
    notes: "No Portland cement - activated by alkali solution. New in ICE v4.1. Up to 60% less carbon than general concrete.",
    fhsRecommended: true,
    typicalApplications: "Precast elements, floor slabs, foundations (where approved)",
  },
  {
    id: "concrete-c20",
    name: "Concrete C20/25 (Lean Mix)",
    category: "Concrete & Cement",
    embodiedCarbon: 0.107,
    unit: "kgCO2e/kg",
    density: 2350,
    typicalApplications: "Blinding, fill, non-structural slabs, kerb bedding",
  },
  {
    id: "concrete-c50",
    name: "Concrete C50/60 (High Strength)",
    category: "Concrete & Cement",
    embodiedCarbon: 0.188,
    unit: "kgCO2e/kg",
    density: 2450,
    notes: "Higher cement content for structural performance",
    typicalApplications: "High-rise columns, post-tensioned slabs, bridges",
  },
  {
    id: "concrete-ggbs-70",
    name: "Concrete with 70% GGBS",
    category: "Concrete & Cement",
    embodiedCarbon: 0.082,
    unit: "kgCO2e/kg",
    density: 2400,
    notes: "ICE v4.1 economic allocation. Very high GGBS replacement - slow early strength gain.",
    fhsRecommended: true,
    typicalApplications: "Mass foundations, raft slabs, marine structures",
  },
  {
    id: "concrete-self-compacting",
    name: "Self-Compacting Concrete (SCC)",
    category: "Concrete & Cement",
    embodiedCarbon: 0.145,
    unit: "kgCO2e/kg",
    density: 2400,
    notes: "Flows under own weight - no vibration needed, higher fines content",
    typicalApplications: "Complex formwork, congested reinforcement, architectural finish",
  },
  {
    id: "sprayed-concrete",
    name: "Sprayed Concrete (Shotcrete)",
    category: "Concrete & Cement",
    embodiedCarbon: 0.155,
    unit: "kgCO2e/kg",
    density: 2300,
    notes: "Pneumatically applied - higher waste factor than cast concrete",
    typicalApplications: "Tunnel linings, retaining walls, slope stabilisation",
  },
  {
    id: "cem-ii",
    name: "Portland Limestone Cement (CEM II/A-L)",
    category: "Concrete & Cement",
    embodiedCarbon: 0.760,
    unit: "kgCO2e/kg",
    density: 1500,
    notes: "Up to 20% limestone replacement - now the default UK cement type",
    typicalApplications: "General purpose cement for concrete, mortar, render",
  },
  {
    id: "cem-iii",
    name: "Blast Furnace Cement (CEM III/A)",
    category: "Concrete & Cement",
    embodiedCarbon: 0.400,
    unit: "kgCO2e/kg",
    density: 1500,
    notes: "36-65% GGBS replacement. ICE v4.1 economic allocation applies.",
    fhsRecommended: true,
    typicalApplications: "Marine, foundations, mass concrete, sulfate resistance",
  },

  /* ═══════════════════════════════════════
     ADDITIONAL STEEL & METALS (v4.1)
     ═══════════════════════════════════════ */
  {
    id: "steel-cold-formed",
    name: "Cold-Formed Steel Sections (LGS)",
    category: "Steel & Metals",
    embodiedCarbon: 1.78,
    unit: "kgCO2e/kg",
    density: 7850,
    notes: "Light gauge steel - additional processing energy over hot-rolled",
    typicalApplications: "Light steel framing, mezzanines, modular construction",
  },
  {
    id: "steel-hollow-section",
    name: "Structural Hollow Section (SHS/RHS/CHS)",
    category: "Steel & Metals",
    embodiedCarbon: 1.68,
    unit: "kgCO2e/kg",
    density: 7850,
    typicalApplications: "Columns, trusses, exposed structural elements",
  },
  {
    id: "steel-plate",
    name: "Steel Plate",
    category: "Steel & Metals",
    embodiedCarbon: 1.55,
    unit: "kgCO2e/kg",
    density: 7850,
    typicalApplications: "Base plates, connection plates, fabricated beams",
  },
  {
    id: "steel-wire-mesh",
    name: "Steel Wire Mesh (Fabric)",
    category: "Steel & Metals",
    embodiedCarbon: 1.99,
    unit: "kgCO2e/kg",
    density: 7850,
    typicalApplications: "Slab reinforcement, screed mesh, fence panels",
  },
  {
    id: "brass",
    name: "Brass (Copper-Zinc Alloy)",
    category: "Steel & Metals",
    embodiedCarbon: 4.40,
    unit: "kgCO2e/kg",
    density: 8500,
    typicalApplications: "Plumbing fittings, valves, ironmongery, decorative",
  },
  {
    id: "titanium-zinc",
    name: "Titanium Zinc (VM Zinc/Rheinzink)",
    category: "Steel & Metals",
    embodiedCarbon: 3.30,
    unit: "kgCO2e/kg",
    density: 7200,
    notes: "Premium architectural material - very long lifespan, fully recyclable",
    typicalApplications: "Standing seam roofing, cladding, rainwater goods",
  },

  /* ═══════════════════════════════════════
     ADDITIONAL INSULATION (v4.1)
     ═══════════════════════════════════════ */
  {
    id: "straw-bale",
    name: "Straw Bale Insulation",
    category: "Insulation",
    embodiedCarbon: 0.006,
    unit: "kgCO2e/kg",
    density: 100,
    notes: "Agricultural by-product - carbon negative when biogenic storage included",
    fhsRecommended: true,
    typicalApplications: "Timber frame infill, self-build, eco-housing",
  },
  {
    id: "hempcrete",
    name: "Hempcrete (Hemp-Lime)",
    category: "Insulation",
    embodiedCarbon: 0.06,
    unit: "kgCO2e/kg",
    density: 330,
    notes: "Carbon-negative wall material - sequesters more CO₂ than emitted in production",
    fhsRecommended: true,
    typicalApplications: "Timber frame infill walls, renovation, self-build",
  },
  {
    id: "vacuum-insulation",
    name: "Vacuum Insulation Panel (VIP)",
    category: "Insulation",
    embodiedCarbon: 7.50,
    unit: "kgCO2e/kg",
    density: 200,
    notes: "5-8x the thermal performance per mm of conventional insulation - very high embodied carbon per kg but minimal per m² of wall",
    typicalApplications: "Ultra-thin refurbishment, heritage, floor build-ups",
  },
  {
    id: "recycled-plastic-insulation",
    name: "Recycled PET Insulation",
    category: "Insulation",
    embodiedCarbon: 1.45,
    unit: "kgCO2e/kg",
    density: 30,
    notes: "Made from recycled plastic bottles - diverts waste from landfill",
    typicalApplications: "Acoustic insulation, timber frame, internal partitions",
  },

  /* ═══════════════════════════════════════
     ADDITIONAL TIMBER (v4.1)
     ═══════════════════════════════════════ */
  {
    id: "accoya",
    name: "Accoya (Acetylated Wood)",
    category: "Timber & Wood",
    embodiedCarbon: 0.85,
    unit: "kgCO2e/kg",
    density: 510,
    notes: "Chemically modified softwood - 50+ year durability class 1. Higher carbon but dramatically longer life than treated softwood.",
    typicalApplications: "External cladding, windows, doors, decking, bridges",
  },
  {
    id: "bamboo-structural",
    name: "Bamboo (Laminated Structural)",
    category: "Timber & Wood",
    embodiedCarbon: 0.52,
    unit: "kgCO2e/kg",
    density: 700,
    notes: "Fast-growing grass - 3-5 year harvest cycle. Transport emissions from Asia reduce benefit.",
    typicalApplications: "Flooring, panels, structural elements, worktops",
  },
  {
    id: "thermally-modified-timber",
    name: "Thermally Modified Timber",
    category: "Timber & Wood",
    embodiedCarbon: 0.68,
    unit: "kgCO2e/kg",
    density: 450,
    notes: "Heat-treated to improve durability without chemicals",
    typicalApplications: "External cladding, decking, saunas, window frames",
  },
  {
    id: "timber-frame-panel",
    name: "Timber Frame Wall Panel (Closed)",
    category: "Timber & Wood",
    embodiedCarbon: 0.38,
    unit: "kgCO2e/kg",
    density: 350,
    notes: "Factory-insulated panel - lower site waste, faster erection",
    fhsRecommended: true,
    typicalApplications: "Residential house building, MMC, modular construction",
  },
  {
    id: "sip-panel",
    name: "Structural Insulated Panel (SIP)",
    category: "Timber & Wood",
    embodiedCarbon: 0.92,
    unit: "kgCO2e/kg",
    density: 200,
    notes: "OSB skins with EPS/PUR core - excellent airtightness",
    typicalApplications: "Walls, roofs, residential, self-build, extensions",
  },

  /* ═══════════════════════════════════════
     ADDITIONAL BRICKS & BLOCKS (v4.1)
     ═══════════════════════════════════════ */
  {
    id: "hempcrete-block",
    name: "Hempcrete Block",
    category: "Bricks & Blocks",
    embodiedCarbon: 0.06,
    unit: "kgCO2e/kg",
    density: 400,
    notes: "Pre-formed hemp-lime blocks - carbon negative",
    fhsRecommended: true,
    typicalApplications: "Non-structural infill, internal walls, renovation",
  },
  {
    id: "unfired-clay-brick",
    name: "Unfired Clay Brick",
    category: "Bricks & Blocks",
    embodiedCarbon: 0.03,
    unit: "kgCO2e/kg",
    density: 1700,
    notes: "Sun-dried or compressed earth - 87% less carbon than fired clay",
    fhsRecommended: true,
    typicalApplications: "Internal walls, thermal mass, eco-builds",
  },
  {
    id: "concrete-block-recycled",
    name: "Concrete Block (Recycled Aggregate)",
    category: "Bricks & Blocks",
    embodiedCarbon: 0.078,
    unit: "kgCO2e/kg",
    density: 1950,
    notes: "Contains recycled demolition aggregate - 17% less carbon",
    fhsRecommended: true,
    typicalApplications: "Internal walls, foundations, below-ground",
  },
  {
    id: "reclaimed-brick",
    name: "Reclaimed Brick",
    category: "Bricks & Blocks",
    embodiedCarbon: 0.01,
    unit: "kgCO2e/kg",
    density: 1900,
    notes: "Salvaged and cleaned - embodied carbon limited to transport and cleaning only",
    fhsRecommended: true,
    typicalApplications: "Feature walls, heritage, residential, garden walls",
  },
];

// Regulatory timeline data
export interface RegulationEvent {
  id: string;
  title: string;
  date: string;
  status: "active" | "upcoming" | "consultation" | "future";
  category: "carbon" | "energy" | "reporting" | "trade";
  description: string;
  impact: string;
  affectedRoles: string[];
}

export const regulations: RegulationEvent[] = [
  {
    id: "fhs-2025",
    title: "Future Homes Standard - Transitional Arrangements",
    date: "2025-06-01",
    status: "active",
    category: "energy",
    description:
      "Transitional provisions allowing approved plans to proceed under current Part L before full FHS takes effect. Plans submitted before the cutoff can use 2021 Part L standards.",
    impact:
      "Window closing for developers - plans submitted after cutoff must meet full FHS requirements.",
    affectedRoles: ["developer", "architect"],
  },
  {
    id: "fhs-published",
    title: "Future Homes & Buildings Standards - Published",
    date: "2026-03-24",
    status: "active",
    category: "energy",
    description:
      "Government has laid the regulations for the Future Homes Standard and Future Buildings Standard, publishing updated Approved Documents L and F (2026). New homes must be built with solar panels, low-carbon heating (heat pumps/heat networks), and high fabric efficiency as standard. Creates at least 75% less carbon emissions than 2013 standards. Home Energy Model (HEM) confirmed as new calculation methodology replacing SAP.",
    impact:
      "Landmark moment for UK construction. Housebuilders must now prepare supply chains for heat pumps, solar PV, and MVHR. Families could save up to £830/year on energy bills. Industry must upskill for new compliance methodology (HEM).",
    affectedRoles: ["developer", "architect", "manufacturer", "contractor"],
  },
  {
    id: "part-z-consultation",
    title: "Part Z (Whole-Life Carbon) - Government Consultation",
    date: "2025-09-01",
    status: "active",
    category: "carbon",
    description:
      "Government consultation on whole-life carbon reporting for large buildings launched. Industry-led Part Z proposal has gained significant Parliamentary support with cross-party backing.",
    impact:
      "Major projects should begin whole-life carbon assessments now to prepare for mandatory requirements.",
    affectedRoles: ["developer", "architect", "contractor"],
  },
  {
    id: "building-safety-act-deadline",
    title: "Building Safety Act - Principal Designer Registration Deadline",
    date: "2025-10-01",
    status: "active",
    category: "reporting",
    description:
      "All Principal Designers and Principal Contractors for higher-risk buildings must be registered with the Building Safety Regulator (BSR).",
    impact:
      "Failure to register means inability to work on HRBs. Check BSR registration status immediately.",
    affectedRoles: ["developer", "architect", "contractor"],
  },
  {
    id: "uknzcbs",
    title: "UK Net Zero Carbon Building Standard (UKNZCBS) - Published",
    date: "2026-01-15",
    status: "active",
    category: "carbon",
    description:
      "UKNZCBS published covering both embodied and operational emissions. Sets verified performance targets for new residential, commercial, and education buildings across energy use intensity, embodied carbon, and airtightness.",
    impact:
      "Defines what 'net zero carbon' means for UK buildings. Voluntary but rapidly becoming market expectation for major developers.",
    affectedRoles: ["developer", "architect", "manufacturer"],
  },
  {
    id: "uk-srs-voluntary",
    title: "UK Sustainability Reporting Standards - Voluntary Adoption",
    date: "2026-03-01",
    status: "active",
    category: "reporting",
    description:
      "UK SRS (based on ISSB standards) now available for voluntary adoption. Companies can begin reporting ahead of mandatory requirements expected in 2027.",
    impact:
      "Early adopters gain competitive advantage with investors and clients. Scope 3 reporting preparation essential for supply chain.",
    affectedRoles: ["manufacturer", "developer", "contractor"],
  },
  {
    id: "fbs-published",
    title: "Future Buildings Standard - Published",
    date: "2026-03-24",
    status: "active",
    category: "energy",
    description:
      "Published alongside the Future Homes Standard. Sets new energy performance requirements for non-domestic buildings including updated Parts L and F. Impact assessment published covering costs, benefits and wider impacts on businesses and the public sector.",
    impact:
      "Commercial developers must now prepare for updated compliance requirements. New non-domestic buildings will need to meet significantly higher energy performance standards.",
    affectedRoles: ["developer", "architect", "contractor"],
  },
  {
    id: "uk-srs-mandatory",
    title: "UK SRS - Mandatory FCA Rules Expected",
    date: "2026-10-01",
    status: "upcoming",
    category: "reporting",
    description:
      "FCA expected to finalise mandatory sustainability reporting rules for large listed companies in autumn 2026, applying for accounting periods from January 2027. Scope 3 emissions reporting included.",
    impact:
      "All major construction companies must prepare Scope 3 supply chain data. Material manufacturers will face data requests from clients.",
    affectedRoles: ["manufacturer", "developer"],
  },
  {
    id: "cbam-registration",
    title: "UK CBAM - Importer Registration Opens",
    date: "2026-10-01",
    status: "upcoming",
    category: "trade",
    description:
      "Importers of steel, aluminium, cement, ceramics, and fertiliser must register ahead of the UK Carbon Border Adjustment Mechanism launch in January 2027.",
    impact:
      "Importers need to understand the carbon content of their supply chain and prepare reporting systems.",
    affectedRoles: ["manufacturer", "contractor"],
  },
  {
    id: "fhs-full",
    title: "Future Homes Standard - Full Compliance Required",
    date: "2028-01-01",
    status: "upcoming",
    category: "energy",
    description:
      "All new homes must meet the full Future Homes Standard after the transition period. Solar panels, low-carbon heating (heat pumps or heat networks), and high fabric efficiency mandatory. No new gas boilers. At least 75% less carbon emissions than 2013 standards. Compliance demonstrated via the Home Energy Model (HEM).",
    impact:
      "Fundamental change to UK housebuilding. Every new home must have solar, heat pump, and meet stringent fabric standards. Housebuilders who haven't adapted their supply chains and designs will face compliance issues.",
    affectedRoles: ["developer", "architect", "manufacturer", "contractor"],
  },
  {
    id: "cbam-launch",
    title: "UK CBAM - Full Launch",
    date: "2027-01-01",
    status: "future",
    category: "trade",
    description:
      "UK Carbon Border Adjustment Mechanism launches. Carbon levy on imports of steel, aluminium, cement, ceramics, hydrogen, electricity, and glass. Based on actual or default emission values.",
    impact:
      "Imported construction materials face carbon pricing. UK domestic manufacturers may gain competitive advantage. Material costs for imported steel/aluminium likely to rise.",
    affectedRoles: ["manufacturer", "contractor"],
  },
  {
    id: "uk-srs-first-reports",
    title: "UK SRS - First Mandatory Reports Due",
    date: "2027-04-01",
    status: "future",
    category: "reporting",
    description:
      "First mandatory sustainability reports due from large listed companies for accounting periods starting January 2027. Scope 1, 2, and 3 emissions reporting required.",
    impact:
      "Construction companies must have emissions data systems in place. Supply chain data requests will cascade to subcontractors and manufacturers.",
    affectedRoles: ["manufacturer", "developer", "contractor"],
  },
  {
    id: "epc-c-minimum",
    title: "EPC Rating C Minimum - Non-Domestic (Proposed)",
    date: "2027-04-01",
    status: "future",
    category: "energy",
    description:
      "Proposed MEES tightening requiring non-domestic rented buildings to achieve minimum EPC Rating C. Government consultation response still awaited - date may shift to 2028.",
    impact:
      "Landlords must retrofit properties or face penalties. Major retrofit wave expected. Demand for energy consultancy and building services design to surge.",
    affectedRoles: ["developer", "contractor"],
  },
  {
    id: "biodiversity-net-gain",
    title: "Biodiversity Net Gain - Small Sites Compliance",
    date: "2027-04-01",
    status: "future",
    category: "reporting",
    description:
      "All developments including small sites must deliver minimum 10% biodiversity net gain, measured using the statutory biodiversity metric. Two-year transition period from February 2024 mandate for major sites.",
    impact:
      "All developers must factor BNG costs and land requirements into project feasibility. Habitat banking market growing rapidly.",
    affectedRoles: ["developer", "architect"],
  },
  {
    id: "part-z-limits",
    title: "Part Z - Mandatory Embodied Carbon Limits (Expected)",
    date: "2028-01-01",
    status: "future",
    category: "carbon",
    description:
      "Expected introduction of mandatory whole-life carbon reporting and embodied carbon limits for buildings over 1,000m². Will require A1-A5 reporting at planning stage and whole-life (A-C) at completion.",
    impact:
      "Material selection becomes carbon-critical. Low-carbon specification, design for disassembly, and material passports will become standard practice.",
    affectedRoles: ["developer", "architect", "manufacturer", "contractor"],
  },
  {
    id: "epc-c-domestic",
    title: "EPC Rating C - Domestic Rented Properties (Proposed)",
    date: "2028-12-01",
    status: "future",
    category: "energy",
    description:
      "Proposed requirement for all rented domestic properties to achieve EPC Rating C. Repeatedly delayed - currently expected no earlier than 2028. Cost cap per property likely.",
    impact:
      "Massive retrofit demand across UK rental stock. Insulation, glazing, and heating system upgrades at scale.",
    affectedRoles: ["developer", "contractor", "manufacturer"],
  },
];

// Carbon intensity types for the API
export interface CarbonIntensityData {
  from: string;
  to: string;
  intensity: {
    forecast: number;
    actual: number;
    index: string;
  };
}

export interface GenerationMix {
  fuel: string;
  perc: number;
}

// Helper functions
export function getIntensityColor(index: string): string {
  switch (index?.toLowerCase()) {
    case "very low":
      return "#22c55e";
    case "low":
      return "#84cc16";
    case "moderate":
      return "#eab308";
    case "high":
      return "#f97316";
    case "very high":
      return "#ef4444";
    default:
      return "#8A8A9A";
  }
}

export function getIntensityBg(index: string): string {
  switch (index?.toLowerCase()) {
    case "very low":
      return "bg-green-100 text-green-800";
    case "low":
      return "bg-lime-100 text-lime-800";
    case "moderate":
      return "bg-yellow-100 text-yellow-800";
    case "high":
      return "bg-orange-100 text-orange-800";
    case "very high":
      return "bg-red-100 text-red-800";
    default:
      return "bg-gray-100 text-gray-800";
  }
}
