// Planning Explorer types + data loader.
//
// Data sources (real only — no fictional seeds):
//
//   1. src/data/applications-real.json (generated by scripts/ingest-planning-data.ts)
//      Real applications pulled from planning.data.gov.uk (the UK government's
//      open planning data service). Conditions are NOT in this dataset and
//      remain empty until the PDF extractor pipeline is run on a decision
//      notice for that application.
//
//   2. src/data/extracted-real.json (optional — generated by scripts/extract-pdfs.ts)
//      Real applications whose decision-notice PDFs have been processed by
//      Claude. These carry the full extracted conditions. Generated on demand
//      by dropping PDFs in _pipeline/decision-notices/ and running the script.
//      Missing on first build — handled with a try/catch require pattern.
//
// Bundled into the page at build time. Swap for an API route backed by Neon
// once the dataset grows past a few thousand records.

import realIngested from "@/data/applications-real.json";

export type Decision = "approved" | "refused" | "withdrawn" | "pending";

export type Sector =
  | "data-centre"
  | "logistics"
  | "btr-pbsa"
  | "healthcare"
  | "education"
  | "renewable-energy"
  | "hotels"
  | "mixed-use";

export type Region =
  | "London"
  | "South East"
  | "South West"
  | "East of England"
  | "East Midlands"
  | "West Midlands"
  | "Yorkshire & Humber"
  | "North West"
  | "North East"
  | "Wales"
  | "Scotland";

export type ConditionType =
  | "noise"
  | "ecology"
  | "bng"
  | "transport"
  | "lighting"
  | "hours"
  | "drainage"
  | "materials"
  | "s106"
  | "heritage"
  | "air-quality"
  | "daylight"
  | "fire"
  | "other";

export interface Condition {
  number: string;
  type: ConditionType;
  summary: string;
  text: string;
}

export type ApplicationSource =
  | "planning.data.gov.uk"
  | "lpa-portal-scrape"
  | "claude-extraction";

export interface Application {
  id: string;
  reference: string;
  lpa: string;
  region: Region | "";
  address: string;
  postcode: string;
  useClass: string;
  sector: Sector;
  description: string;
  applicant: string;
  agent: string;
  decision: Decision;
  decisionDate: string;
  grossFloorAreaSqm?: number;
  conditions: Condition[];
  source: ApplicationSource;
  /** Deep link back to the original LPA portal record, when known. */
  sourceUrl?: string;
}

interface BundleShape<T = Application> {
  generatedAt: string;
  note?: string;
  source?: string;
  applications: T[];
}

export const SECTOR_LABELS: Record<Sector, string> = {
  "data-centre": "Data centres",
  logistics: "Logistics & warehousing",
  "btr-pbsa": "BTR / PBSA",
  healthcare: "Healthcare",
  education: "Education",
  "renewable-energy": "Renewable energy & BESS",
  hotels: "Hotels & hospitality",
  "mixed-use": "Mixed-use major regen",
};

export const CONDITION_LABELS: Record<ConditionType, string> = {
  noise: "Noise",
  ecology: "Ecology",
  bng: "Biodiversity Net Gain",
  transport: "Transport / HGV",
  lighting: "Lighting",
  hours: "Hours of use",
  drainage: "Drainage / SuDS",
  materials: "Materials",
  s106: "Section 106 / affordable",
  heritage: "Heritage",
  "air-quality": "Air quality",
  daylight: "Daylight / sunlight",
  fire: "Fire safety",
  other: "Other",
};

export function loadApplications(): Application[] {
  const ingested = (
    realIngested as BundleShape<Omit<Application, "source">>
  ).applications.map<Application>((a) => ({
    ...a,
    source: "planning.data.gov.uk",
  }));

  // Optional sources — may not exist on a fresh checkout. Use try/catch
  // around require so missing files don't break the build.
  let scraped: Application[] = [];
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const m = require("@/data/applications-scraped.json") as BundleShape<
      Omit<Application, "source">
    >;
    scraped = m.applications.map<Application>((a) => ({
      ...a,
      source: "lpa-portal-scrape",
    }));
  } catch {
    /* no LPA-scrape data yet */
  }

  let extracted: Application[] = [];
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const m = require("@/data/extracted-real.json") as BundleShape<
      Omit<Application, "source">
    >;
    extracted = m.applications.map<Application>((a) => ({
      ...a,
      source: "claude-extraction",
    }));
  } catch {
    /* no extracted-real.json yet */
  }

  // Dedupe by id; later sources win (extracted has real conditions; scraped
  // has real applicants — both override gov.uk if same id).
  const byId = new Map<string, Application>();
  for (const app of [...ingested, ...scraped, ...extracted]) {
    byId.set(app.id, app);
  }
  return Array.from(byId.values());
}

export interface DatasetCounts {
  total: number;
  openData: number;
  scraped: number;
  extracted: number;
  withApplicant: number;
  conditions: number;
  lpas: string[];
  /** Most recent generatedAt across the loaded JSON sources. */
  lastRefreshed: string;
}

export function getDatasetCounts(): DatasetCounts {
  const apps = loadApplications();

  // Pull generatedAt from each loaded source; the page surfaces the most
  // recent value as "last refreshed".
  const timestamps: string[] = [];
  const pushIfPresent = (mod: { generatedAt?: string }) => {
    if (mod?.generatedAt) timestamps.push(mod.generatedAt);
  };
  pushIfPresent(realIngested as BundleShape<Omit<Application, "source">>);
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const scraped = require("@/data/applications-scraped.json") as BundleShape<
      Omit<Application, "source">
    >;
    pushIfPresent(scraped);
  } catch {
    /* ignore */
  }
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const extracted = require("@/data/extracted-real.json") as BundleShape<
      Omit<Application, "source">
    >;
    pushIfPresent(extracted);
  } catch {
    /* ignore */
  }

  return {
    total: apps.length,
    openData: apps.filter((a) => a.source === "planning.data.gov.uk").length,
    scraped: apps.filter((a) => a.source === "lpa-portal-scrape").length,
    extracted: apps.filter((a) => a.source === "claude-extraction").length,
    withApplicant: apps.filter((a) => a.applicant.trim().length > 0).length,
    conditions: apps.reduce((n, a) => n + a.conditions.length, 0),
    lpas: Array.from(new Set(apps.map((a) => a.lpa))).sort(),
    lastRefreshed: timestamps.sort().reverse()[0] ?? "",
  };
}
