-- Director's Daily Brief — live web app data model.
-- Replaces the static HTML brief generated by _scripts/build-director-brief.py
-- in the Client-System repo. Tasks ingested from email/Fireflies/manual sources;
-- scheduled into FlowSavvy-style time blocks; ticked off interactively.
-- Run once against the Neon database backing this project (psql or Neon SQL editor).

CREATE TABLE IF NOT EXISTS director_tasks (
  id            BIGSERIAL PRIMARY KEY,
  ref           TEXT UNIQUE,
  title         TEXT NOT NULL,
  body          TEXT,
  owner         TEXT,
  client        TEXT,
  priority      SMALLINT,
  deadline      DATE,
  status        TEXT NOT NULL DEFAULT 'open',
  source        TEXT NOT NULL DEFAULT 'manual',
  source_ref    TEXT,
  source_url    TEXT,
  est_minutes   INT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at  TIMESTAMPTZ,
  CONSTRAINT director_tasks_status_chk
    CHECK (status IN ('open', 'in_progress', 'awaiting_review', 'completed', 'dropped')),
  CONSTRAINT director_tasks_source_chk
    CHECK (source IN ('manual', 'email', 'fireflies', 'master_task_list', 'cron'))
);

CREATE INDEX IF NOT EXISTS director_tasks_status_idx
  ON director_tasks (status, deadline NULLS LAST);
CREATE INDEX IF NOT EXISTS director_tasks_owner_idx
  ON director_tasks (owner);
CREATE INDEX IF NOT EXISTS director_tasks_source_ref_idx
  ON director_tasks (source, source_ref);

CREATE TABLE IF NOT EXISTS director_task_blocks (
  id              BIGSERIAL PRIMARY KEY,
  task_id         BIGINT NOT NULL REFERENCES director_tasks(id) ON DELETE CASCADE,
  scheduled_date  DATE NOT NULL,
  start_minute    SMALLINT NOT NULL,
  duration_min    SMALLINT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT director_task_blocks_start_chk
    CHECK (start_minute BETWEEN 0 AND 1439),
  CONSTRAINT director_task_blocks_duration_chk
    CHECK (duration_min BETWEEN 5 AND 480)
);

CREATE INDEX IF NOT EXISTS director_task_blocks_date_idx
  ON director_task_blocks (scheduled_date, start_minute);

CREATE TABLE IF NOT EXISTS director_task_notes (
  id          BIGSERIAL PRIMARY KEY,
  task_id     BIGINT NOT NULL REFERENCES director_tasks(id) ON DELETE CASCADE,
  body        TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS director_task_notes_task_idx
  ON director_task_notes (task_id, created_at DESC);

CREATE TABLE IF NOT EXISTS director_ingestion_state (
  source        TEXT PRIMARY KEY,
  last_synced   TIMESTAMPTZ NOT NULL,
  cursor        TEXT,
  CONSTRAINT director_ingestion_source_chk
    CHECK (source IN ('email_inbox', 'email_sent', 'fireflies', 'master_task_list'))
);
