// Generated by _market-research/ai-construction-test/gen_chart_data.py
// Do not hand-edit: regenerate so labels stay tied to model IDs.
// Deliberately not a client module, so server pages can import these
// values directly.

// ──────────────────────────────────────────────────
// Data — Fabrick UK Construction AI Accuracy Test
// Wave 2026-07. Generated 2026-07-29T12:00:27+00:00 by
// _market-research/ai-construction-test/gen_chart_data.py
// Do not hand-edit: regenerate so labels stay tied to model IDs.
// ──────────────────────────────────────────────────

export interface ModelRow {
  id: string;
  name: string;
  /** Exact model identifier sent to the provider's API. */
  modelId: string;
  vendor: string;
  score: number;
  correct: number;
  partial: number;
  wrong: number;
  paid: boolean;
  /** Models within the tie band are statistically indistinguishable. */
  band: number;
}

export const MODELS: ModelRow[] = [
  { id: "claude_opus_5", name: "Claude Opus 5", modelId: "claude-opus-5", vendor: "Anthropic", score: 86.5, correct: 618, partial: 89, wrong: 59, paid: true, band: 1 },
  { id: "claude_fable_5", name: "Claude Fable 5", modelId: "claude-fable-5", vendor: "Anthropic", score: 86.4, correct: 625, partial: 93, wrong: 59, paid: true, band: 1 },
  { id: "gpt_56_sol", name: "GPT-5.6 Sol", modelId: "openai/gpt-5.6-sol", vendor: "OpenAI", score: 85.1, correct: 629, partial: 107, wrong: 66, paid: true, band: 1 },
  { id: "claude_opus_48", name: "Claude Opus 4.8", modelId: "claude-opus-4-8", vendor: "Anthropic", score: 83.7, correct: 585, partial: 117, wrong: 67, paid: true, band: 2 },
  { id: "kimi_3", name: "Kimi 3", modelId: "moonshotai/kimi-k3", vendor: "Moonshot AI", score: 83.5, correct: 584, partial: 99, wrong: 76, paid: true, band: 2 },
  { id: "gemini_36_flash", name: "Gemini 3.6 Flash", modelId: "gemini-3.6-flash", vendor: "Google", score: 81.9, correct: 551, partial: 132, wrong: 70, paid: false, band: 3 },
  { id: "gemini_31_pro", name: "Gemini 3.1 Pro", modelId: "google/gemini-3.1-pro-preview", vendor: "Google", score: 81.2, correct: 531, partial: 135, wrong: 71, paid: true, band: 3 },
  { id: "gpt_56_luna", name: "GPT-5.6 Luna", modelId: "openai/gpt-5.6-luna", vendor: "OpenAI", score: 80.7, correct: 578, partial: 122, wrong: 92, paid: false, band: 3 },
  { id: "grok_45", name: "Grok 4.5", modelId: "grok-4.5", vendor: "xAI", score: 80.7, correct: 564, partial: 140, wrong: 82, paid: true, band: 3 },
  { id: "perplexity_pro", name: "Perplexity Sonar Pro", modelId: "sonar-pro", vendor: "Perplexity", score: 80.6, correct: 538, partial: 115, wrong: 86, paid: true, band: 3 },
  { id: "gpt_56_terra", name: "GPT-5.6 Terra", modelId: "openai/gpt-5.6-terra", vendor: "OpenAI", score: 80.5, correct: 572, partial: 122, wrong: 92, paid: true, band: 3 },
  { id: "perplexity", name: "Perplexity Sonar", modelId: "sonar", vendor: "Perplexity", score: 79.7, correct: 532, partial: 127, wrong: 88, paid: false, band: 4 },
  { id: "claude_sonnet_5", name: "Claude Sonnet 5", modelId: "claude-sonnet-5", vendor: "Anthropic", score: 78.1, correct: 528, partial: 119, wrong: 105, paid: true, band: 5 },
  { id: "deepseek_v4_pro", name: "DeepSeek V4 Pro", modelId: "deepseek/deepseek-v4-pro", vendor: "DeepSeek", score: 74.5, correct: 480, partial: 172, wrong: 108, paid: true, band: 6 },
  { id: "deepseek_v4_flash", name: "DeepSeek V4 Flash", modelId: "deepseek/deepseek-v4-flash", vendor: "DeepSeek", score: 68.7, correct: 419, partial: 195, wrong: 138, paid: false, band: 7 },
  { id: "mistral_large", name: "Mistral Large", modelId: "mistralai/mistral-large-2512", vendor: "Mistral", score: 65.2, correct: 384, partial: 212, wrong: 156, paid: true, band: 8 },
  { id: "mistral_medium", name: "Mistral Medium", modelId: "mistral-medium-2604", vendor: "Mistral", score: 60.6, correct: 351, partial: 220, wrong: 190, paid: false, band: 9 },
  { id: "claude_haiku_45", name: "Claude Haiku 4.5", modelId: "claude-haiku-4-5", vendor: "Anthropic", score: 49.7, correct: 272, partial: 208, wrong: 277, paid: false, band: 10 },
];

export const MODEL_ORDER = MODELS.map((m) => m.id);
export const MODEL_NAMES: Record<string, string> = Object.fromEntries(MODELS.map((m) => [m.id, m.name]));

export interface CategoryRow {
  questions: number;
  scores: Record<string, number>;
}

export const CATEGORIES: Record<string, CategoryRow> = {
  "Accessibility & Inclusive Design": { questions: 39, scores: { claude_opus_5: 78, claude_fable_5: 79, gpt_56_sol: 74, claude_opus_48: 71, kimi_3: 70, gemini_36_flash: 72, gemini_31_pro: 68, gpt_56_luna: 74, grok_45: 73, perplexity_pro: 62, gpt_56_terra: 77, perplexity: 59, claude_sonnet_5: 69, deepseek_v4_pro: 62, deepseek_v4_flash: 60, mistral_large: 49, mistral_medium: 47, claude_haiku_45: 40 } },
  "British Standards - Concrete & Steel": { questions: 48, scores: { claude_opus_5: 91, claude_fable_5: 90, gpt_56_sol: 87, claude_opus_48: 87, kimi_3: 90, gemini_36_flash: 92, gemini_31_pro: 90, gpt_56_luna: 84, grok_45: 88, perplexity_pro: 81, gpt_56_terra: 81, perplexity: 80, claude_sonnet_5: 91, deepseek_v4_pro: 87, deepseek_v4_flash: 73, mistral_large: 71, mistral_medium: 57, claude_haiku_45: 57 } },
  "British Standards - Other Materials": { questions: 45, scores: { claude_opus_5: 93, claude_fable_5: 92, gpt_56_sol: 91, claude_opus_48: 92, kimi_3: 95, gemini_36_flash: 93, gemini_31_pro: 87, gpt_56_luna: 94, grok_45: 91, perplexity_pro: 90, gpt_56_terra: 85, perplexity: 92, claude_sonnet_5: 82, deepseek_v4_pro: 85, deepseek_v4_flash: 80, mistral_large: 77, mistral_medium: 66, claude_haiku_45: 55 } },
  "Building Regulations - Fire Safety": { questions: 49, scores: { claude_opus_5: 93, claude_fable_5: 90, gpt_56_sol: 88, claude_opus_48: 91, kimi_3: 89, gemini_36_flash: 87, gemini_31_pro: 86, gpt_56_luna: 87, grok_45: 91, perplexity_pro: 92, gpt_56_terra: 86, perplexity: 83, claude_sonnet_5: 75, deepseek_v4_pro: 83, deepseek_v4_flash: 74, mistral_large: 74, mistral_medium: 58, claude_haiku_45: 46 } },
  "Building Regulations - Other Parts": { questions: 44, scores: { claude_opus_5: 83, claude_fable_5: 82, gpt_56_sol: 77, claude_opus_48: 80, kimi_3: 76, gemini_36_flash: 86, gemini_31_pro: 74, gpt_56_luna: 70, grok_45: 76, perplexity_pro: 74, gpt_56_terra: 76, perplexity: 76, claude_sonnet_5: 71, deepseek_v4_pro: 66, deepseek_v4_flash: 56, mistral_large: 68, mistral_medium: 58, claude_haiku_45: 44 } },
  "Building Regulations - Thermal": { questions: 47, scores: { claude_opus_5: 84, claude_fable_5: 80, gpt_56_sol: 81, claude_opus_48: 79, kimi_3: 80, gemini_36_flash: 78, gemini_31_pro: 87, gpt_56_luna: 78, grok_45: 80, perplexity_pro: 83, gpt_56_terra: 81, perplexity: 90, claude_sonnet_5: 66, deepseek_v4_pro: 64, deepseek_v4_flash: 60, mistral_large: 42, mistral_medium: 63, claude_haiku_45: 39 } },
  "Construction Technology": { questions: 35, scores: { claude_opus_5: 87, claude_fable_5: 86, gpt_56_sol: 79, claude_opus_48: 83, kimi_3: 83, gemini_36_flash: 72, gemini_31_pro: 68, gpt_56_luna: 76, grok_45: 70, perplexity_pro: 79, gpt_56_terra: 74, perplexity: 69, claude_sonnet_5: 74, deepseek_v4_pro: 67, deepseek_v4_flash: 61, mistral_large: 54, mistral_medium: 61, claude_haiku_45: 52 } },
  "Contracts & Procurement": { questions: 44, scores: { claude_opus_5: 94, claude_fable_5: 92, gpt_56_sol: 86, claude_opus_48: 90, kimi_3: 89, gemini_36_flash: 86, gemini_31_pro: 82, gpt_56_luna: 80, grok_45: 84, perplexity_pro: 80, gpt_56_terra: 81, perplexity: 78, claude_sonnet_5: 89, deepseek_v4_pro: 74, deepseek_v4_flash: 59, mistral_large: 58, mistral_medium: 59, claude_haiku_45: 39 } },
  "Demolition & Refurbishment": { questions: 28, scores: { claude_opus_5: 94, claude_fable_5: 90, gpt_56_sol: 96, claude_opus_48: 83, kimi_3: 86, gemini_36_flash: 76, gemini_31_pro: 71, gpt_56_luna: 90, grok_45: 75, perplexity_pro: 86, gpt_56_terra: 90, perplexity: 85, claude_sonnet_5: 82, deepseek_v4_pro: 75, deepseek_v4_flash: 65, mistral_large: 73, mistral_medium: 66, claude_haiku_45: 57 } },
  "Environmental & Contamination": { questions: 34, scores: { claude_opus_5: 94, claude_fable_5: 95, gpt_56_sol: 92, claude_opus_48: 95, kimi_3: 95, gemini_36_flash: 80, gemini_31_pro: 80, gpt_56_luna: 86, grok_45: 88, perplexity_pro: 89, gpt_56_terra: 88, perplexity: 92, claude_sonnet_5: 94, deepseek_v4_pro: 81, deepseek_v4_flash: 79, mistral_large: 67, mistral_medium: 59, claude_haiku_45: 48 } },
  "Fire Safety - Post-Grenfell": { questions: 41, scores: { claude_opus_5: 88, claude_fable_5: 90, gpt_56_sol: 93, claude_opus_48: 92, kimi_3: 90, gemini_36_flash: 85, gemini_31_pro: 88, gpt_56_luna: 85, grok_45: 85, perplexity_pro: 96, gpt_56_terra: 80, perplexity: 89, claude_sonnet_5: 84, deepseek_v4_pro: 79, deepseek_v4_flash: 77, mistral_large: 71, mistral_medium: 68, claude_haiku_45: 47 } },
  "Health & Safety / CDM": { questions: 46, scores: { claude_opus_5: 99, claude_fable_5: 100, gpt_56_sol: 100, claude_opus_48: 100, kimi_3: 99, gemini_36_flash: 98, gemini_31_pro: 99, gpt_56_luna: 99, grok_45: 98, perplexity_pro: 99, gpt_56_terra: 99, perplexity: 100, claude_sonnet_5: 96, deepseek_v4_pro: 94, deepseek_v4_flash: 89, mistral_large: 90, mistral_medium: 93, claude_haiku_45: 74 } },
  "MEP & Building Services": { questions: 41, scores: { claude_opus_5: 74, claude_fable_5: 76, gpt_56_sol: 76, claude_opus_48: 70, kimi_3: 73, gemini_36_flash: 69, gemini_31_pro: 74, gpt_56_luna: 76, grok_45: 67, perplexity_pro: 71, gpt_56_terra: 75, perplexity: 70, claude_sonnet_5: 74, deepseek_v4_pro: 73, deepseek_v4_flash: 65, mistral_large: 53, mistral_medium: 49, claude_haiku_45: 34 } },
  "Materials & Products": { questions: 40, scores: { claude_opus_5: 86, claude_fable_5: 78, gpt_56_sol: 82, claude_opus_48: 77, kimi_3: 71, gemini_36_flash: 86, gemini_31_pro: 83, gpt_56_luna: 79, grok_45: 76, perplexity_pro: 72, gpt_56_terra: 78, perplexity: 75, claude_sonnet_5: 74, deepseek_v4_pro: 68, deepseek_v4_flash: 72, mistral_large: 65, mistral_medium: 59, claude_haiku_45: 44 } },
  "NHBC Standards": { questions: 39, scores: { claude_opus_5: 68, claude_fable_5: 75, gpt_56_sol: 79, claude_opus_48: 74, kimi_3: 66, gemini_36_flash: 71, gemini_31_pro: 68, gpt_56_luna: 72, grok_45: 67, perplexity_pro: 71, gpt_56_terra: 74, perplexity: 68, claude_sonnet_5: 57, deepseek_v4_pro: 61, deepseek_v4_flash: 69, mistral_large: 67, mistral_medium: 51, claude_haiku_45: 61 } },
  "Planning & Permitted Development": { questions: 51, scores: { claude_opus_5: 94, claude_fable_5: 94, gpt_56_sol: 95, claude_opus_48: 87, kimi_3: 94, gemini_36_flash: 91, gemini_31_pro: 94, gpt_56_luna: 92, grok_45: 88, perplexity_pro: 98, gpt_56_terra: 86, perplexity: 96, claude_sonnet_5: 82, deepseek_v4_pro: 83, deepseek_v4_flash: 76, mistral_large: 70, mistral_medium: 66, claude_haiku_45: 68 } },
  "Roofing & Cladding": { questions: 44, scores: { claude_opus_5: 66, claude_fable_5: 70, gpt_56_sol: 77, claude_opus_48: 76, kimi_3: 68, gemini_36_flash: 64, gemini_31_pro: 61, gpt_56_luna: 56, grok_45: 67, perplexity_pro: 56, gpt_56_terra: 67, perplexity: 55, claude_sonnet_5: 64, deepseek_v4_pro: 62, deepseek_v4_flash: 54, mistral_large: 59, mistral_medium: 52, claude_haiku_45: 45 } },
  "Structural Design & Loading": { questions: 44, scores: { claude_opus_5: 88, claude_fable_5: 94, gpt_56_sol: 86, claude_opus_48: 87, kimi_3: 92, gemini_36_flash: 86, gemini_31_pro: 89, gpt_56_luna: 83, grok_45: 85, perplexity_pro: 85, gpt_56_terra: 80, perplexity: 83, claude_sonnet_5: 86, deepseek_v4_pro: 76, deepseek_v4_flash: 78, mistral_large: 78, mistral_medium: 63, claude_haiku_45: 62 } },
  "Sustainability & Carbon": { questions: 47, scores: { claude_opus_5: 90, claude_fable_5: 91, gpt_56_sol: 90, claude_opus_48: 88, kimi_3: 86, gemini_36_flash: 81, gemini_31_pro: 85, gpt_56_luna: 90, grok_45: 91, perplexity_pro: 85, gpt_56_terra: 83, perplexity: 80, claude_sonnet_5: 80, deepseek_v4_pro: 78, deepseek_v4_flash: 66, mistral_large: 66, mistral_medium: 65, claude_haiku_45: 48 } },
  "Waterproofing & Below-Ground": { questions: 42, scores: { claude_opus_5: 75, claude_fable_5: 73, gpt_56_sol: 71, claude_opus_48: 64, kimi_3: 72, gemini_36_flash: 67, gemini_31_pro: 70, gpt_56_luna: 64, grok_45: 63, perplexity_pro: 61, gpt_56_terra: 68, perplexity: 67, claude_sonnet_5: 68, deepseek_v4_pro: 66, deepseek_v4_flash: 63, mistral_large: 51, mistral_medium: 47, claude_haiku_45: 33 } },
};

/** Headline figures, kept next to the data they come from. */
export const STUDY = {
  wave: "2026-07",
  questions: 951,
  models: 18,
  categories: 20,
  responses: 13747,
  bestScore: 86.5,
  bestModel: "Claude Opus 5",
  paidAvg: 80.5,
  freeAvg: 70.2,
  paidCount: 12,
  freeCount: 6,
  gapPp: 10.3,
  judgeAgreement: 80.3,
  tieBandPp: 1.5,
  bands: 10,
  stabilityRho: 0.9587,
  stabilityUnmoved: 12,
  stabilityCorrections: 27,
  excludedOnDisagreement: 3369,
} as const;
