"use client";

import { useMemo, useState } from "react";
import {
  TrendingUp,
  TrendingDown,
  ArrowUpDown,
  ArrowUp,
  ArrowDown,
  MapPin,
  Info,
} from "lucide-react";
import snapshot from "@/data/epc-snapshot.json";

// ---------------------------------------------------------------------------
// Snapshot is generated by scripts/ingest-epc.ts. The JSON shape lives
// alongside that script - keep this type in sync if the script changes.
// ---------------------------------------------------------------------------

type Band = "A" | "B" | "C" | "D" | "E" | "F" | "G";

interface CityRow {
  city: string;
  region: string;
  total: number;
  bandCounts: Record<Band, number>;
  belowCPct: number;
  urgentPct: number;
  compliantPct: number;
  postcodesSampled: number;
  postcodesWithData: number;
}

interface Snapshot {
  generatedAt: string;
  source: string;
  notes: string[];
  national: {
    total: number;
    belowCPct: number;
    urgentPct: number;
    compliantPct: number;
    bandCounts: Record<Band, number>;
  };
  cities: CityRow[];
}

const data = snapshot as unknown as Snapshot;

// ---------------------------------------------------------------------------
// Headline national stat - one big number
// ---------------------------------------------------------------------------

function NationalHeadline() {
  const generated = new Date(data.generatedAt).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  const dPct = (data.national.bandCounts.D / data.national.total) * 100;

  return (
    <div className="rounded-2xl bg-charcoal p-6 md:p-10 text-white">
      <div className="flex items-center gap-2 mb-3">
        <MapPin className="h-4 w-4 text-pink" />
        <span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-pink">
          The retrofit map
        </span>
      </div>

      <div className="grid gap-8 md:grid-cols-[auto_1fr] items-end">
        <div>
          <p className="text-sm text-gray-400 mb-1">
            Of the {data.national.total.toLocaleString()} domestic certificates
            sampled across {data.cities.length} UK cities
          </p>
          <div className="flex items-baseline gap-3">
            <span className="font-[family-name:var(--font-playfair)] text-6xl md:text-7xl font-bold text-pink tabular-nums">
              {data.national.belowCPct.toFixed(0)}%
            </span>
            <span className="text-base md:text-lg text-white">
              sit below band C
            </span>
          </div>
          <p className="mt-3 max-w-xl text-sm text-gray-400">
            That is the size of the MEES-driven retrofit pipeline visible in
            this snapshot. Band D properties (currently MEES-compliant) come
            into scope when the proposed 2027 and 2030 thresholds bite.
          </p>
        </div>

        <div className="grid grid-cols-3 gap-4 md:gap-6">
          <Stat
            label="Already compliant"
            sub="A, B or C"
            value={`${data.national.compliantPct.toFixed(0)}%`}
            tone="teal"
          />
          <Stat
            label="At-risk band D"
            sub="MEES 2027/2030"
            value={`${dPct.toFixed(0)}%`}
            tone="amber"
          />
          <Stat
            label="Non-compliant"
            sub="E, F or G"
            value={`${data.national.urgentPct.toFixed(0)}%`}
            tone="pink"
          />
        </div>
      </div>

      <div className="mt-6 flex items-start gap-2 rounded-lg bg-navy-light/50 px-3 py-2.5 max-w-3xl">
        <Info className="h-3.5 w-3.5 text-gray-400 mt-0.5 shrink-0" />
        <p className="text-[11px] text-gray-400 leading-relaxed">
          Sample of 8-12 residential postcodes per city, deduped by UPRN.
          MHCLG domestic register only - England and Wales. Non-domestic stock
          is not in this view. Snapshot dated {generated}.
        </p>
      </div>
    </div>
  );
}

function Stat({
  label,
  sub,
  value,
  tone,
}: {
  label: string;
  sub: string;
  value: string;
  tone: "teal" | "amber" | "pink";
}) {
  const toneText = {
    teal: "text-teal",
    amber: "text-amber-400",
    pink: "text-pink",
  }[tone];
  return (
    <div className="rounded-xl bg-navy-light/40 p-4">
      <p className="text-[10px] font-semibold uppercase tracking-wider text-gray-400">
        {label}
      </p>
      <p
        className={`mt-1 font-[family-name:var(--font-playfair)] text-3xl font-bold ${toneText} tabular-nums`}
      >
        {value}
      </p>
      <p className="mt-1 text-[10px] text-gray-500">{sub}</p>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Two leaderboards (top + bottom by belowC%)
// ---------------------------------------------------------------------------

function LeaderboardCard({
  title,
  eyebrow,
  blurb,
  cities,
  tone,
  Icon,
}: {
  title: string;
  eyebrow: string;
  blurb: string;
  cities: CityRow[];
  tone: "pink" | "teal";
  Icon: typeof TrendingUp;
}) {
  const accent = tone === "pink" ? "text-pink" : "text-teal";
  const bar =
    tone === "pink"
      ? "bg-gradient-to-r from-pink/30 to-pink"
      : "bg-gradient-to-r from-teal/30 to-teal";
  const ring = tone === "pink" ? "ring-pink/20" : "ring-teal/20";

  // Width is scaled to the max in the visible list so the bars are readable
  const max = Math.max(...cities.map((c) => c.belowCPct));

  return (
    <div className={`rounded-2xl bg-white ring-1 ${ring} p-5 md:p-6`}>
      <div className="flex items-start justify-between gap-3 mb-1">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Icon className={`h-4 w-4 ${accent}`} />
            <span
              className={`text-[10px] font-semibold uppercase tracking-[0.18em] ${accent}`}
            >
              {eyebrow}
            </span>
          </div>
          <h3 className="font-[family-name:var(--font-playfair)] text-xl md:text-2xl font-bold text-navy">
            {title}
          </h3>
        </div>
      </div>
      <p className="text-xs text-warm-gray mb-4 max-w-md">{blurb}</p>

      <ol className="space-y-2">
        {cities.map((c, i) => {
          const widthPct = max > 0 ? (c.belowCPct / max) * 100 : 0;
          return (
            <li
              key={c.city}
              className="flex items-center gap-3 rounded-lg bg-cream/50 px-3 py-2"
            >
              <span className="w-5 shrink-0 text-[11px] font-bold text-warm-gray tabular-nums">
                {i + 1}
              </span>
              <div className="flex-1 min-w-0">
                <div className="flex items-baseline justify-between gap-3">
                  <p className="text-sm font-semibold text-navy truncate">
                    {c.city}
                  </p>
                  <p
                    className={`text-sm font-bold ${accent} tabular-nums shrink-0`}
                  >
                    {c.belowCPct.toFixed(0)}%
                  </p>
                </div>
                <div className="mt-1.5 h-1.5 w-full overflow-hidden rounded-full bg-cream-dark">
                  <div
                    className={`h-full ${bar}`}
                    style={{ width: `${widthPct}%` }}
                  />
                </div>
                <p className="mt-1 text-[10px] text-warm-gray">
                  {c.region} · {c.total.toLocaleString()} certs
                </p>
              </div>
            </li>
          );
        })}
      </ol>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Sortable table of all cities
// ---------------------------------------------------------------------------

type SortKey = "city" | "total" | "compliantPct" | "dPct" | "urgentPct" | "belowCPct";
type SortDir = "asc" | "desc";

function SortHeader({
  label,
  sortKey,
  activeKey,
  sortDir,
  onSort,
  align = "left",
}: {
  label: string;
  sortKey: SortKey;
  activeKey: SortKey;
  sortDir: SortDir;
  onSort: (k: SortKey) => void;
  align?: "left" | "right";
}) {
  const active = activeKey === sortKey;
  const Arrow = !active ? ArrowUpDown : sortDir === "asc" ? ArrowUp : ArrowDown;
  return (
    <th
      scope="col"
      className={`px-3 py-2.5 text-[10px] font-semibold uppercase tracking-wider text-warm-gray ${
        align === "right" ? "text-right" : "text-left"
      }`}
    >
      <button
        type="button"
        onClick={() => onSort(sortKey)}
        className={`inline-flex items-center gap-1 ${
          align === "right" ? "flex-row-reverse" : ""
        } hover:text-navy transition-colors ${active ? "text-navy" : ""}`}
      >
        <span>{label}</span>
        <Arrow className="h-3 w-3" />
      </button>
    </th>
  );
}

function SortableTable() {
  const [sortKey, setSortKey] = useState<SortKey>("belowCPct");
  const [sortDir, setSortDir] = useState<SortDir>("desc");

  const rows = useMemo(() => {
    const enriched = data.cities.map((c) => ({
      ...c,
      dPct: c.total > 0 ? (c.bandCounts.D / c.total) * 100 : 0,
    }));

    return [...enriched].sort((a, b) => {
      const dir = sortDir === "asc" ? 1 : -1;
      if (sortKey === "city") return a.city.localeCompare(b.city) * dir;
      const av = a[sortKey];
      const bv = b[sortKey];
      return (av < bv ? -1 : av > bv ? 1 : 0) * dir;
    });
  }, [sortKey, sortDir]);

  const toggleSort = (key: SortKey) => {
    if (sortKey === key) {
      setSortDir(sortDir === "asc" ? "desc" : "asc");
    } else {
      setSortKey(key);
      setSortDir(key === "city" ? "asc" : "desc");
    }
  };

  const headerProps = { activeKey: sortKey, sortDir, onSort: toggleSort };

  return (
    <div className="rounded-2xl bg-white ring-1 ring-cream-dark overflow-hidden">
      <div className="px-5 py-4 border-b border-cream-dark">
        <h3 className="font-[family-name:var(--font-playfair)] text-xl font-bold text-navy">
          All cities, ranked
        </h3>
        <p className="text-xs text-warm-gray mt-0.5">
          {data.cities.length} UK cities. Click any column to re-sort. Default
          ranks highest retrofit demand first.
        </p>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="bg-cream/40">
            <tr>
              <SortHeader label="City" sortKey="city" {...headerProps} />
              <SortHeader label="Region" sortKey="city" {...headerProps} />
              <SortHeader label="Certs" sortKey="total" align="right" {...headerProps} />
              <SortHeader label="A-C compliant" sortKey="compliantPct" align="right" {...headerProps} />
              <SortHeader label="D at risk" sortKey="dPct" align="right" {...headerProps} />
              <SortHeader label="E-G urgent" sortKey="urgentPct" align="right" {...headerProps} />
              <SortHeader label="% below C" sortKey="belowCPct" align="right" {...headerProps} />
            </tr>
          </thead>
          <tbody>
            {rows.map((r, i) => (
              <tr
                key={r.city}
                className={`border-t border-cream-dark/60 ${
                  i % 2 === 0 ? "bg-white" : "bg-cream/20"
                }`}
              >
                <td className="px-3 py-2.5 text-sm font-medium text-navy whitespace-nowrap">
                  {r.city}
                </td>
                <td className="px-3 py-2.5 text-xs text-warm-gray whitespace-nowrap">
                  {r.region}
                </td>
                <td className="px-3 py-2.5 text-xs text-warm-gray text-right tabular-nums">
                  {r.total.toLocaleString()}
                </td>
                <td className="px-3 py-2.5 text-sm text-teal-dark text-right tabular-nums">
                  {r.compliantPct.toFixed(0)}%
                </td>
                <td className="px-3 py-2.5 text-sm text-amber-700 text-right tabular-nums">
                  {r.dPct.toFixed(0)}%
                </td>
                <td className="px-3 py-2.5 text-sm text-pink text-right tabular-nums">
                  {r.urgentPct.toFixed(0)}%
                </td>
                <td className="px-3 py-2.5 text-sm font-bold text-navy text-right tabular-nums">
                  {r.belowCPct.toFixed(0)}%
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Public component - the main leaderboard block
// ---------------------------------------------------------------------------

export function RetrofitLeaderboard() {
  const sorted = [...data.cities].sort((a, b) => b.belowCPct - a.belowCPct);
  const top10 = sorted.slice(0, 10);
  const bottom10 = sorted.slice(-10).reverse();

  return (
    <div className="space-y-6">
      <NationalHeadline />

      <div className="grid gap-6 lg:grid-cols-2">
        <LeaderboardCard
          title="Highest retrofit demand"
          eyebrow="Where the work is"
          blurb="Cities with the largest share of homes below band C. The biggest local pipelines for MEES-driven upgrade work."
          cities={top10}
          tone="pink"
          Icon={TrendingUp}
        />
        <LeaderboardCard
          title="Already-compliant stock"
          eyebrow="Smaller pipelines"
          blurb="Cities with the most homes already at A, B or C. Smaller addressable retrofit market today, but D-band stock will still come into scope by 2030."
          cities={bottom10}
          tone="teal"
          Icon={TrendingDown}
        />
      </div>

      <SortableTable />
    </div>
  );
}
